package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class Cities extends BaseModel implements Serializable {
    private Integer id;

    private String name;

    private String pinyin;

    private Integer provinceId;

    private Integer sort;

    private Date createdAt;

    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cities
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities.id
     *
     * @return the value of cities.id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities.id
     *
     * @param id the value for cities.id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities.name
     *
     * @return the value of cities.name
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities.name
     *
     * @param name the value for cities.name
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities.pinyin
     *
     * @return the value of cities.pinyin
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities.pinyin
     *
     * @param pinyin the value for cities.pinyin
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities.province_id
     *
     * @return the value of cities.province_id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities.province_id
     *
     * @param provinceId the value for cities.province_id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities.sort
     *
     * @return the value of cities.sort
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities.sort
     *
     * @param sort the value for cities.sort
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities.created_at
     *
     * @return the value of cities.created_at
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities.created_at
     *
     * @param createdAt the value for cities.created_at
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities.updated_at
     *
     * @return the value of cities.updated_at
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities.updated_at
     *
     * @param updatedAt the value for cities.updated_at
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}