package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class CrmAdmin extends BaseModel implements Serializable {
    /**
     * 主键id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long id;

    /**
     * 用户名
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String adminName;

    /**
     * 密码
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String adminPassword;

    /**
     * 用户状态
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Byte adminStatus;

    /**
     * 职务
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String adminJob;

    /**
     * 真实姓名
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String adminRealName;

    /**
     * 手机
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String adminPhone;

    /**
     * 所属部门
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long adminDep;

    /**
     * 是否为部门管理员
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Byte isDepManager;

    /**
     * 上次登录时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date adminLastTime;

    /**
     * 删除标识
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Boolean isDel;

    /**
     * 创建时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date createTime;

    /**
     * 更新时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date updateTime;

    /**
     * 角色列表
     */
    private List<CrmRole> roleList;
    
    /**
     * 角色id
     */
    private Long role_id;
    
    /**
     * 部门名称
     */
    private String depName;
    
    private Byte roleType; 
    
    //是否重置密码
    private int isResetPassword;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_admin
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin.id
     *
     * @return the value of crm_admin.id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin.id
     *
     * @param id the value for crm_admin.id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin.admin_name
     *
     * @return the value of crm_admin.admin_name
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin.admin_name
     *
     * @param adminName the value for crm_admin.admin_name
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin.admin_password
     *
     * @return the value of crm_admin.admin_password
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin.admin_password
     *
     * @param adminPassword the value for crm_admin.admin_password
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword == null ? null : adminPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin.admin_status
     *
     * @return the value of crm_admin.admin_status
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Byte getAdminStatus() {
        return adminStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin.admin_status
     *
     * @param adminStatus the value for crm_admin.admin_status
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAdminStatus(Byte adminStatus) {
        this.adminStatus = adminStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin.admin_job
     *
     * @return the value of crm_admin.admin_job
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getAdminJob() {
        return adminJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin.admin_job
     *
     * @param adminJob the value for crm_admin.admin_job
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAdminJob(String adminJob) {
        this.adminJob = adminJob == null ? null : adminJob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin.admin_real_name
     *
     * @return the value of crm_admin.admin_real_name
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getAdminRealName() {
        return adminRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin.admin_real_name
     *
     * @param adminRealName the value for crm_admin.admin_real_name
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAdminRealName(String adminRealName) {
        this.adminRealName = adminRealName == null ? null : adminRealName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin.admin_phone
     *
     * @return the value of crm_admin.admin_phone
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getAdminPhone() {
        return adminPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin.admin_phone
     *
     * @param adminPhone the value for crm_admin.admin_phone
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAdminPhone(String adminPhone) {
        this.adminPhone = adminPhone == null ? null : adminPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin.admin_dep
     *
     * @return the value of crm_admin.admin_dep
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getAdminDep() {
        return adminDep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin.admin_dep
     *
     * @param adminDep the value for crm_admin.admin_dep
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAdminDep(Long adminDep) {
        this.adminDep = adminDep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin.is_dep_manager
     *
     * @return the value of crm_admin.is_dep_manager
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Byte getIsDepManager() {
        return isDepManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin.is_dep_manager
     *
     * @param isDepManager the value for crm_admin.is_dep_manager
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setIsDepManager(Byte isDepManager) {
        this.isDepManager = isDepManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin.admin_last_time
     *
     * @return the value of crm_admin.admin_last_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getAdminLastTime() {
        return adminLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin.admin_last_time
     *
     * @param adminLastTime the value for crm_admin.admin_last_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAdminLastTime(Date adminLastTime) {
        this.adminLastTime = adminLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin.is_del
     *
     * @return the value of crm_admin.is_del
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin.is_del
     *
     * @param isDel the value for crm_admin.is_del
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin.create_time
     *
     * @return the value of crm_admin.create_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin.create_time
     *
     * @param createTime the value for crm_admin.create_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin.update_time
     *
     * @return the value of crm_admin.update_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin.update_time
     *
     * @param updateTime the value for crm_admin.update_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public List<CrmRole> getRoleList() {
		return roleList;
	}

	public void setRoleList(List<CrmRole> roleList) {
		this.roleList = roleList;
	}

	public Long getRole_id() {
		return role_id;
	}

	public void setRole_id(Long role_id) {
		this.role_id = role_id;
	}

	public String getDepName() {
		return depName;
	}

	public void setDepName(String depName) {
		this.depName = depName;
	}

	public Byte getRoleType() {
		return roleType;
	}

	public void setRoleType(Byte roleType) {
		this.roleType = roleType;
	}

	public int getIsResetPassword() {
		return isResetPassword;
	}

	public void setIsResetPassword(int isResetPassword) {
		this.isResetPassword = isResetPassword;
	}


    
}