package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class CrmAutharea extends BaseModel implements Serializable {
    /**
     * 主键id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long id;

    /**
     * 合同id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long contId;

    /**
     * 省
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Integer provinceId;

    /**
     * 市
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Integer cityId;

    /**
     * 区县
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Integer areaId;

    /**
     * 删除标识
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Boolean isDel;

    /**
     * 创建时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date createTime;

    /**
     * 更新时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_autharea
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_autharea.id
     *
     * @return the value of crm_autharea.id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_autharea.id
     *
     * @param id the value for crm_autharea.id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_autharea.cont_id
     *
     * @return the value of crm_autharea.cont_id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getContId() {
        return contId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_autharea.cont_id
     *
     * @param contId the value for crm_autharea.cont_id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setContId(Long contId) {
        this.contId = contId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_autharea.province_id
     *
     * @return the value of crm_autharea.province_id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_autharea.province_id
     *
     * @param provinceId the value for crm_autharea.province_id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_autharea.city_id
     *
     * @return the value of crm_autharea.city_id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_autharea.city_id
     *
     * @param cityId the value for crm_autharea.city_id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_autharea.area_id
     *
     * @return the value of crm_autharea.area_id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_autharea.area_id
     *
     * @param areaId the value for crm_autharea.area_id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_autharea.is_del
     *
     * @return the value of crm_autharea.is_del
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_autharea.is_del
     *
     * @param isDel the value for crm_autharea.is_del
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_autharea.create_time
     *
     * @return the value of crm_autharea.create_time
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_autharea.create_time
     *
     * @param createTime the value for crm_autharea.create_time
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_autharea.update_time
     *
     * @return the value of crm_autharea.update_time
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_autharea.update_time
     *
     * @param updateTime the value for crm_autharea.update_time
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}