package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class CrmAuth extends BaseModel implements Serializable {
    /**
     * 主键id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long id;

    private Long authId;
    /**
     * 权限code
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Integer authCode;

    /**
     * 权限父节点
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long parentId;

    /**
     * 权限名称
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String authName;

    /**
     * 权限类型 1 菜单权限 2 按钮权限
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Byte authType;

    /**
     * 权限描述
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String authDesc;

    /**
     * 权限url
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String authUrl;

    /**
     * 菜单图标
     */
    private String authImg;
    
    /**
     * 排序
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Integer authSort;

    /**
     * 删除标识 0 否 1 是
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Boolean isDel;

    /**
     * 创建时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date createTime;

    /**
     * 更新时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date updateTime; 

    private List<CrmAuth> children;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_auth
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_auth.id
     *
     * @return the value of crm_auth.id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_auth.id
     *
     * @param id the value for crm_auth.id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_auth.auth_code
     *
     * @return the value of crm_auth.auth_code
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Integer getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_auth.auth_code
     *
     * @param authCode the value for crm_auth.auth_code
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAuthCode(Integer authCode) {
        this.authCode = authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_auth.parent_id
     *
     * @return the value of crm_auth.parent_id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_auth.parent_id
     *
     * @param parentId the value for crm_auth.parent_id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_auth.auth_name
     *
     * @return the value of crm_auth.auth_name
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getAuthName() {
        return authName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_auth.auth_name
     *
     * @param authName the value for crm_auth.auth_name
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAuthName(String authName) {
        this.authName = authName == null ? null : authName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_auth.auth_type
     *
     * @return the value of crm_auth.auth_type
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Byte getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_auth.auth_type
     *
     * @param authType the value for crm_auth.auth_type
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAuthType(Byte authType) {
        this.authType = authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_auth.auth_desc
     *
     * @return the value of crm_auth.auth_desc
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getAuthDesc() {
        return authDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_auth.auth_desc
     *
     * @param authDesc the value for crm_auth.auth_desc
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAuthDesc(String authDesc) {
        this.authDesc = authDesc == null ? null : authDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_auth.auth_url
     *
     * @return the value of crm_auth.auth_url
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getAuthUrl() {
        return authUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_auth.auth_url
     *
     * @param authUrl the value for crm_auth.auth_url
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAuthUrl(String authUrl) {
        this.authUrl = authUrl == null ? null : authUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_auth.auth_sort
     *
     * @return the value of crm_auth.auth_sort
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Integer getAuthSort() {
        return authSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_auth.auth_sort
     *
     * @param authSort the value for crm_auth.auth_sort
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAuthSort(Integer authSort) {
        this.authSort = authSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_auth.is_del
     *
     * @return the value of crm_auth.is_del
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_auth.is_del
     *
     * @param isDel the value for crm_auth.is_del
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_auth.create_time
     *
     * @return the value of crm_auth.create_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_auth.create_time
     *
     * @param createTime the value for crm_auth.create_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_auth.update_time
     *
     * @return the value of crm_auth.update_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_auth.update_time
     *
     * @param updateTime the value for crm_auth.update_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    
	public List<CrmAuth> getChildren() {
		return children;
	}

	public void setChildren(List<CrmAuth> children) {
		this.children = children;
	}

	public String getAuthImg() {
		return authImg;
	}

	public void setAuthImg(String authImg) {
		this.authImg = authImg;
	}

	public Long getAuthId() {
		return authId;
	}

	public void setAuthId(Long authId) {
		this.authId = authId;
	}

	@Override
	public String toString() {
		return "CrmAuth [id=" + id + ", authCode=" + authCode + ", parentId="
				+ parentId + ", authName=" + authName + ", authType="
				+ authType + ", authDesc=" + authDesc + ", authUrl=" + authUrl
				+ ", authSort=" + authSort + ", isDel=" + isDel
				+ ", createTime=" + createTime + ", updateTime=" + updateTime
				+ "]";
	}
    
    
}