package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class CrmAdminRole extends BaseModel implements Serializable {
    /**
     * 主键id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long id;

    /**
     * 管理员id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long adminId;

    /**
     * 角色id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long roleId;

    /**
     * 删除标识 0 否 1 是
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Boolean isDel;

    /**
     * 创建时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date createTime;

    /**
     * 更新时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_admin_role
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin_role.id
     *
     * @return the value of crm_admin_role.id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin_role.id
     *
     * @param id the value for crm_admin_role.id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin_role.admin_id
     *
     * @return the value of crm_admin_role.admin_id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin_role.admin_id
     *
     * @param adminId the value for crm_admin_role.admin_id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin_role.role_id
     *
     * @return the value of crm_admin_role.role_id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin_role.role_id
     *
     * @param roleId the value for crm_admin_role.role_id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin_role.is_del
     *
     * @return the value of crm_admin_role.is_del
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin_role.is_del
     *
     * @param isDel the value for crm_admin_role.is_del
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin_role.create_time
     *
     * @return the value of crm_admin_role.create_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin_role.create_time
     *
     * @param createTime the value for crm_admin_role.create_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin_role.update_time
     *
     * @return the value of crm_admin_role.update_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin_role.update_time
     *
     * @param updateTime the value for crm_admin_role.update_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}