package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class CrmBusiProduct extends BaseModel implements Serializable {
    /**
     * 主键id
     *
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    private Long id;

    /**
     * 商机id
     *
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    private Long busiId;

    /**
     * 产品id
     *
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    private Long prodId;

    /**
     * 产品套餐ID
     *
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    private Long prodVersionId;

    /**
     * 删除标识
     *
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    private Boolean isDel;

    /**
     * 创建时间
     *
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    private Date createTime;

    /**
     * 更新时间
     *
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_busi_product
     *
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_busi_product.id
     *
     * @return the value of crm_busi_product.id
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_busi_product.id
     *
     * @param id the value for crm_busi_product.id
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_busi_product.busi_id
     *
     * @return the value of crm_busi_product.busi_id
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    public Long getBusiId() {
        return busiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_busi_product.busi_id
     *
     * @param busiId the value for crm_busi_product.busi_id
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    public void setBusiId(Long busiId) {
        this.busiId = busiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_busi_product.prod_id
     *
     * @return the value of crm_busi_product.prod_id
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    public Long getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_busi_product.prod_id
     *
     * @param prodId the value for crm_busi_product.prod_id
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    public void setProdId(Long prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_busi_product.prod_version_id
     *
     * @return the value of crm_busi_product.prod_version_id
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    public Long getProdVersionId() {
        return prodVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_busi_product.prod_version_id
     *
     * @param prodVersionId the value for crm_busi_product.prod_version_id
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    public void setProdVersionId(Long prodVersionId) {
        this.prodVersionId = prodVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_busi_product.is_del
     *
     * @return the value of crm_busi_product.is_del
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_busi_product.is_del
     *
     * @param isDel the value for crm_busi_product.is_del
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_busi_product.create_time
     *
     * @return the value of crm_busi_product.create_time
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_busi_product.create_time
     *
     * @param createTime the value for crm_busi_product.create_time
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_busi_product.update_time
     *
     * @return the value of crm_busi_product.update_time
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_busi_product.update_time
     *
     * @param updateTime the value for crm_busi_product.update_time
     * @mbggenerated Wed Jul 29 14:31:47 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}