package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class CrmBusiness extends BaseModel implements Serializable {
    /**
     * 主键id
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    private Long id;

    /**
     * 线索id
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    private Long clueId;

    /**
     * 商机编号
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    private String busiNumber;

    /**
     * 编号自增码
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    private Integer numCode;

    /**
     * 注册时间
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    private Date busiRegitime;

    /**
     * 商机状态
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    private Byte busiStatus;

    private String busiStatusStr;//虚属性，商机状态，文本

    /**
     * 商机来源
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    private Byte busiSource;

    private String busiSourceStr;//虚属性，商机来源，文本

    /**
     * 当前归属人
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    private Long owner;

    /**
     * 当前归属人姓名
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    private String ownerName;

    /**
     * 录入人
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    private Long adminId;

    /**
     * 录入人姓名
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    private String adminName;

    /**
     * 商机类型
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    private Byte busiType;

    private String busiTypeStr;//虚属性 商机类型，文本

    /**
     * 备注
     */
    private String remark;

    /**
     * 删除标识
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    private Boolean isDel;

    /**
     * 创建时间
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    private Date createTime;

    /**
     * 更新时间
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    private Date updateTime;

    /**
     * 商机分配时间
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    private Date allotTime;
    
    /**
     * 合同退回修改备注
     */
    private String returnChangeRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_business
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    private static final long serialVersionUID = 1L;

    //以下都是虚属性
    private String custName;//客户名称

    private Date createTimestart;//注册时间开始
    private Date createTimeend; //注册时间结束 用于查询条件
    private Long callBargain;//预购套餐
    private Byte isDepManager;//是否是管理员查询 0不是 1是
    private List<CrmProductVersion> productVersionList;
    private List<CrmProduct> productList;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_business.id
     *
     * @return the value of crm_business.id
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_business.id
     *
     * @param id the value for crm_business.id
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_business.clue_id
     *
     * @return the value of crm_business.clue_id
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public Long getClueId() {
        return clueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_business.clue_id
     *
     * @param clueId the value for crm_business.clue_id
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public void setClueId(Long clueId) {
        this.clueId = clueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_business.busi_number
     *
     * @return the value of crm_business.busi_number
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public String getBusiNumber() {
        return busiNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_business.busi_number
     *
     * @param busiNumber the value for crm_business.busi_number
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public void setBusiNumber(String busiNumber) {
        this.busiNumber = busiNumber == null ? null : busiNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_business.num_code
     *
     * @return the value of crm_business.num_code
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public Integer getNumCode() {
        return numCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_business.num_code
     *
     * @param numCode the value for crm_business.num_code
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public void setNumCode(Integer numCode) {
        this.numCode = numCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_business.busi_regitime
     *
     * @return the value of crm_business.busi_regitime
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public Date getBusiRegitime() {
        return busiRegitime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_business.busi_regitime
     *
     * @param busiRegitime the value for crm_business.busi_regitime
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public void setBusiRegitime(Date busiRegitime) {
        this.busiRegitime = busiRegitime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_business.busi_status
     *
     * @return the value of crm_business.busi_status
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public Byte getBusiStatus() {
        return busiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_business.busi_status
     *
     * @param busiStatus the value for crm_business.busi_status
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public void setBusiStatus(Byte busiStatus) {
        this.busiStatus = busiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_business.busi_source
     *
     * @return the value of crm_business.busi_source
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public Byte getBusiSource() {
        return busiSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_business.busi_source
     *
     * @param busiSource the value for crm_business.busi_source
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public void setBusiSource(Byte busiSource) {
        this.busiSource = busiSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_business.owner
     *
     * @return the value of crm_business.owner
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public Long getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_business.owner
     *
     * @param owner the value for crm_business.owner
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public void setOwner(Long owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_business.owner_name
     *
     * @return the value of crm_business.owner_name
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_business.owner_name
     *
     * @param ownerName the value for crm_business.owner_name
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_business.busi_type
     *
     * @return the value of crm_business.busi_type
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public Byte getBusiType() {
        return busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_business.busi_type
     *
     * @param busiType the value for crm_business.busi_type
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public void setBusiType(Byte busiType) {
        this.busiType = busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_business.is_del
     *
     * @return the value of crm_business.is_del
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_business.is_del
     *
     * @param isDel the value for crm_business.is_del
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_business.create_time
     *
     * @return the value of crm_business.create_time
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_business.create_time
     *
     * @param createTime the value for crm_business.create_time
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_business.update_time
     *
     * @return the value of crm_business.update_time
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_business.update_time
     *
     * @param updateTime the value for crm_business.update_time
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_business.allot_time
     *
     * @return the value of crm_business.allot_time
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public Date getAllotTime() {
        return allotTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_business.allot_time
     *
     * @param allotTime the value for crm_business.allot_time
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    public void setAllotTime(Date allotTime) {
        this.allotTime = allotTime;
    }

    public String getBusiStatusStr() {
        return busiStatusStr;
    }

    public void setBusiStatusStr(String busiStatusStr) {
        this.busiStatusStr = busiStatusStr;
    }

    public String getBusiSourceStr() {
        return busiSourceStr;
    }

    public void setBusiSourceStr(String busiSourceStr) {
        this.busiSourceStr = busiSourceStr;
    }

    public String getCustName() {
        return custName;
    }

    public void setCustName(String custName) {
        this.custName = custName;
    }

    public String getBusiTypeStr() {
        return busiTypeStr;
    }

    public void setBusiTypeStr(String busiTypeStr) {
        this.busiTypeStr = busiTypeStr;
    }

    public Date getCreateTimestart() {
        return createTimestart;
    }

    public void setCreateTimestart(Date createTimestart) {
        this.createTimestart = createTimestart;
    }

    public Long getCallBargain() {
        return callBargain;
    }

    public void setCallBargain(Long callBargain) {
        this.callBargain = callBargain;
    }

    public Date getCreateTimeend() {
        return createTimeend;
    }

    public void setCreateTimeend(Date createTimeend) {
        this.createTimeend = createTimeend;
    }

    public List<CrmProductVersion> getProductVersionList() {
        return productVersionList;
    }

    public void setProductVersionList(List<CrmProductVersion> productVersionList) {
        this.productVersionList = productVersionList;
    }

    public Long getAdminId() {
        return adminId;
    }

    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    public String getAdminName() {
        return adminName;
    }

    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

	public String getReturnChangeRemark() {
		return returnChangeRemark;
	}

	public void setReturnChangeRemark(String returnChangeRemark) {
		this.returnChangeRemark = returnChangeRemark;
	}

    public Byte getIsDepManager() {
        return isDepManager;
    }

    public void setIsDepManager(Byte isDepManager) {
        this.isDepManager = isDepManager;
    }

    public List<CrmProduct> getProductList() {
        return productList;
    }

    public void setProductList(List<CrmProduct> productList) {
        this.productList = productList;
    }
}