package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class CrmClueProduct extends BaseModel implements Serializable {
    /**
     * 主键id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long id;

    /**
     * 线索id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long clueId;

    /**
     * 产品id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long productId;

    /**
     * 删除标识
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Boolean isDel;

    /**
     * 创建时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date createTime;

    /**
     * 更新时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_clue_product
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_clue_product.id
     *
     * @return the value of crm_clue_product.id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_clue_product.id
     *
     * @param id the value for crm_clue_product.id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_clue_product.clue_id
     *
     * @return the value of crm_clue_product.clue_id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getClueId() {
        return clueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_clue_product.clue_id
     *
     * @param clueId the value for crm_clue_product.clue_id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setClueId(Long clueId) {
        this.clueId = clueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_clue_product.product_id
     *
     * @return the value of crm_clue_product.product_id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_clue_product.product_id
     *
     * @param productId the value for crm_clue_product.product_id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_clue_product.is_del
     *
     * @return the value of crm_clue_product.is_del
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_clue_product.is_del
     *
     * @param isDel the value for crm_clue_product.is_del
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_clue_product.create_time
     *
     * @return the value of crm_clue_product.create_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_clue_product.create_time
     *
     * @param createTime the value for crm_clue_product.create_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_clue_product.update_time
     *
     * @return the value of crm_clue_product.update_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_clue_product.update_time
     *
     * @param updateTime the value for crm_clue_product.update_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}