package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class CrmCallback extends BaseModel implements Serializable {
    /**
     * 主键id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long id;

    /**
     * 线索id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long targetId;

    /**
     * 回访人
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long adminId;

    /**
     * 回访内容
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String callContent;

    /**
     * 成交意向
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Byte callBargain;

    /**
     * 回访时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date callTime;

    /**
     * 下次回访时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date callNextTime;

    /**
     * 删除标识
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Boolean isDel;

    /**
     * 创建时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date createTime;

    /**
     * 更新时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date updateTime;

    /**
     * 回访类型
     */
    private Byte releType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_callback
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private static final long serialVersionUID = 1L;

    //虚属性
    private String adminName; //回访人姓名
    private String callBargainStr;//成交意向文本

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_callback.id
     *
     * @return the value of crm_callback.id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_callback.id
     *
     * @param id the value for crm_callback.id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_callback.admin_id
     *
     * @return the value of crm_callback.admin_id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_callback.admin_id
     *
     * @param adminId the value for crm_callback.admin_id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_callback.call_content
     *
     * @return the value of crm_callback.call_content
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getCallContent() {
        return callContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_callback.call_content
     *
     * @param callContent the value for crm_callback.call_content
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCallContent(String callContent) {
        this.callContent = callContent == null ? null : callContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_callback.call_bargain
     *
     * @return the value of crm_callback.call_bargain
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Byte getCallBargain() {
        return callBargain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_callback.call_bargain
     *
     * @param callBargain the value for crm_callback.call_bargain
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCallBargain(Byte callBargain) {
        this.callBargain = callBargain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_callback.call_time
     *
     * @return the value of crm_callback.call_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getCallTime() {
        return callTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_callback.call_time
     *
     * @param callTime the value for crm_callback.call_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCallTime(Date callTime) {
        this.callTime = callTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_callback.call_next_time
     *
     * @return the value of crm_callback.call_next_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getCallNextTime() {
        return callNextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_callback.call_next_time
     *
     * @param callNextTime the value for crm_callback.call_next_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCallNextTime(Date callNextTime) {
        this.callNextTime = callNextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_callback.is_del
     *
     * @return the value of crm_callback.is_del
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_callback.is_del
     *
     * @param isDel the value for crm_callback.is_del
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_callback.create_time
     *
     * @return the value of crm_callback.create_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_callback.create_time
     *
     * @param createTime the value for crm_callback.create_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_callback.update_time
     *
     * @return the value of crm_callback.update_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_callback.update_time
     *
     * @param updateTime the value for crm_callback.update_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getAdminName() {
        return adminName;
    }

    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    public String getCallBargainStr() {
        return callBargainStr;
    }

    public void setCallBargainStr(String callBargainStr) {
        this.callBargainStr = callBargainStr;
    }

    public Long getTargetId() {
        return targetId;
    }

    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    public Byte getReleType() {
        return releType;
    }

    public void setReleType(Byte releType) {
        this.releType = releType;
    }
}