package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class CrmContractFile extends BaseModel implements Serializable {
    private Long id;

    /**
     * 附件类型 0 合同附件
     *
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    private Byte fileType;

    /**
     * 目标ID，根据file_type 附件类型有所不同
     *
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    private Long targetId;

    /**
     * 文件真实名称
     *
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    private String fileName;

    /**
     * 文件随机名称（防止文件名重复）
     *
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    private String fileNameRandom;

    /**
     * 创建时间
     *
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    private Date createdAt;

    /**
     * 更新时间
     *
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    private Date updatedAt;

    /**
     * 状态
     *
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_contract_file
     *
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_contract_file.id
     *
     * @return the value of crm_contract_file.id
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_contract_file.id
     *
     * @param id the value for crm_contract_file.id
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_contract_file.file_type
     *
     * @return the value of crm_contract_file.file_type
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    public Byte getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_contract_file.file_type
     *
     * @param fileType the value for crm_contract_file.file_type
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    public void setFileType(Byte fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_contract_file.target_id
     *
     * @return the value of crm_contract_file.target_id
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_contract_file.target_id
     *
     * @param targetId the value for crm_contract_file.target_id
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_contract_file.file_name
     *
     * @return the value of crm_contract_file.file_name
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_contract_file.file_name
     *
     * @param fileName the value for crm_contract_file.file_name
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_contract_file.file_name_random
     *
     * @return the value of crm_contract_file.file_name_random
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    public String getFileNameRandom() {
        return fileNameRandom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_contract_file.file_name_random
     *
     * @param fileNameRandom the value for crm_contract_file.file_name_random
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    public void setFileNameRandom(String fileNameRandom) {
        this.fileNameRandom = fileNameRandom == null ? null : fileNameRandom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_contract_file.created_at
     *
     * @return the value of crm_contract_file.created_at
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_contract_file.created_at
     *
     * @param createdAt the value for crm_contract_file.created_at
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_contract_file.updated_at
     *
     * @return the value of crm_contract_file.updated_at
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_contract_file.updated_at
     *
     * @param updatedAt the value for crm_contract_file.updated_at
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_contract_file.status
     *
     * @return the value of crm_contract_file.status
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_contract_file.status
     *
     * @param status the value for crm_contract_file.status
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}