package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class CrmCustomer extends BaseModel implements Serializable {
    /**
     * 主键id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long id;

    /**
     * 姓名
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String custName;

    /**
     * 客户角色
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Byte custRole;

    /**
     * 虚属性，角色，文本
     */
    private String custRoleName;

    /**
     * 电话号码
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String custPhone;

    /**
     * qq号码
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String custQq;

    /**
     * 邮箱
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String custEmail;

    /**
     * 职务
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String custJob;

    /**
     * 删除标识 0 否 1 是
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Boolean isDel;

    /**
     * 创建时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date createTime;

    /**
     * 更新时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_customer
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.id
     *
     * @return the value of crm_customer.id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.id
     *
     * @param id the value for crm_customer.id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.cust_name
     *
     * @return the value of crm_customer.cust_name
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.cust_name
     *
     * @param custName the value for crm_customer.cust_name
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.cust_role
     *
     * @return the value of crm_customer.cust_role
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Byte getCustRole() {
        return custRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.cust_role
     *
     * @param custRole the value for crm_customer.cust_role
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCustRole(Byte custRole) {
        this.custRole = custRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.cust_phone
     *
     * @return the value of crm_customer.cust_phone
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getCustPhone() {
        return custPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.cust_phone
     *
     * @param custPhone the value for crm_customer.cust_phone
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCustPhone(String custPhone) {
        this.custPhone = custPhone == null ? null : custPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.cust_qq
     *
     * @return the value of crm_customer.cust_qq
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getCustQq() {
        return custQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.cust_qq
     *
     * @param custQq the value for crm_customer.cust_qq
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCustQq(String custQq) {
        this.custQq = custQq == null ? null : custQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.cust_email
     *
     * @return the value of crm_customer.cust_email
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getCustEmail() {
        return custEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.cust_email
     *
     * @param custEmail the value for crm_customer.cust_email
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCustEmail(String custEmail) {
        this.custEmail = custEmail == null ? null : custEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.cust_job
     *
     * @return the value of crm_customer.cust_job
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getCustJob() {
        return custJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.cust_job
     *
     * @param custJob the value for crm_customer.cust_job
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCustJob(String custJob) {
        this.custJob = custJob == null ? null : custJob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.is_del
     *
     * @return the value of crm_customer.is_del
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.is_del
     *
     * @param isDel the value for crm_customer.is_del
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.create_time
     *
     * @return the value of crm_customer.create_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.create_time
     *
     * @param createTime the value for crm_customer.create_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.update_time
     *
     * @return the value of crm_customer.update_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.update_time
     *
     * @param updateTime the value for crm_customer.update_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getCustRoleName() {
        return custRoleName;
    }

    public void setCustRoleName(String custRoleName) {
        this.custRoleName = custRoleName;
    }

    @Override
    public String toString() {
        return "CrmCustomer{" +
                "id=" + id +
                ", custName='" + custName + '\'' +
                ", custRole=" + custRole +
                ", custPhone='" + custPhone + '\'' +
                ", custQq='" + custQq + '\'' +
                ", custEmail='" + custEmail + '\'' +
                ", custJob='" + custJob + '\'' +
                ", isDel=" + isDel +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                '}';
    }


}