package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class CrmContProduct extends BaseModel implements Serializable {
    /**
     * 主键id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long id;

    /**
     * 合同id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long contId;

    /**
     * 产品id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long prodId;

    /**
     * 套餐id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long versId;

    /**
     * 实际金额
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long actualAmount;

    /**
     * 购买数量
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Integer buyCount;

    /**
     * 折扣
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String prodDiscount;

    /**
     * 总人天
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Integer sumMenday;

    /**
     * 人天单价
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long priceMenday;

    /**
     * 试用周期
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Integer accTryPeriod;

    /**
     * 试用账号数量
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Integer accTryCount;

    /**
     * 删除标识
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Boolean isDel;

    /**
     * 创建时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date createTime;

    /**
     * 更新时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date updateTime;


    /********自定义属性************************/
    private String versName;
    private Long versPrice;
    private String productName;
    private Long productPrice;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_cont_product
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_cont_product.id
     *
     * @return the value of crm_cont_product.id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_cont_product.id
     *
     * @param id the value for crm_cont_product.id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_cont_product.cont_id
     *
     * @return the value of crm_cont_product.cont_id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getContId() {
        return contId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_cont_product.cont_id
     *
     * @param contId the value for crm_cont_product.cont_id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setContId(Long contId) {
        this.contId = contId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_cont_product.prod_id
     *
     * @return the value of crm_cont_product.prod_id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_cont_product.prod_id
     *
     * @param prodId the value for crm_cont_product.prod_id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setProdId(Long prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_cont_product.actual_amount
     *
     * @return the value of crm_cont_product.actual_amount
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getActualAmount() {
        return actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_cont_product.actual_amount
     *
     * @param actualAmount the value for crm_cont_product.actual_amount
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setActualAmount(Long actualAmount) {
        this.actualAmount = actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_cont_product.buy_count
     *
     * @return the value of crm_cont_product.buy_count
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Integer getBuyCount() {
        return buyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_cont_product.buy_count
     *
     * @param buyCount the value for crm_cont_product.buy_count
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setBuyCount(Integer buyCount) {
        this.buyCount = buyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_cont_product.prod_discount
     *
     * @return the value of crm_cont_product.prod_discount
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getProdDiscount() {
        return prodDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_cont_product.prod_discount
     *
     * @param prodDiscount the value for crm_cont_product.prod_discount
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setProdDiscount(String prodDiscount) {
        this.prodDiscount = prodDiscount == null ? null : prodDiscount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_cont_product.sum_menday
     *
     * @return the value of crm_cont_product.sum_menday
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Integer getSumMenday() {
        return sumMenday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_cont_product.sum_menday
     *
     * @param sumMenday the value for crm_cont_product.sum_menday
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setSumMenday(Integer sumMenday) {
        this.sumMenday = sumMenday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_cont_product.price_menday
     *
     * @return the value of crm_cont_product.price_menday
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getPriceMenday() {
        return priceMenday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_cont_product.price_menday
     *
     * @param priceMenday the value for crm_cont_product.price_menday
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setPriceMenday(Long priceMenday) {
        this.priceMenday = priceMenday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_cont_product.acc_try_period
     *
     * @return the value of crm_cont_product.acc_try_period
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Integer getAccTryPeriod() {
        return accTryPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_cont_product.acc_try_period
     *
     * @param accTryPeriod the value for crm_cont_product.acc_try_period
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAccTryPeriod(Integer accTryPeriod) {
        this.accTryPeriod = accTryPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_cont_product.acc_try_count
     *
     * @return the value of crm_cont_product.acc_try_count
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Integer getAccTryCount() {
        return accTryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_cont_product.acc_try_count
     *
     * @param accTryCount the value for crm_cont_product.acc_try_count
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setAccTryCount(Integer accTryCount) {
        this.accTryCount = accTryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_cont_product.is_del
     *
     * @return the value of crm_cont_product.is_del
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_cont_product.is_del
     *
     * @param isDel the value for crm_cont_product.is_del
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_cont_product.create_time
     *
     * @return the value of crm_cont_product.create_time
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_cont_product.create_time
     *
     * @param createTime the value for crm_cont_product.create_time
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_cont_product.update_time
     *
     * @return the value of crm_cont_product.update_time
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_cont_product.update_time
     *
     * @param updateTime the value for crm_cont_product.update_time
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getVersName() {
        return versName;
    }

    public void setVersName(String versName) {
        this.versName = versName;
    }

    public Long getVersId() {
        return versId;
    }

    public void setVersId(Long versId) {
        this.versId = versId;
    }

    public Long getVersPrice() {
        return versPrice;
    }

    public void setVersPrice(Long versPrice) {
        this.versPrice = versPrice;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Long getProductPrice() {
        return productPrice;
    }

    public void setProductPrice(Long productPrice) {
        this.productPrice = productPrice;
    }
}