package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class CrmDep extends BaseModel implements Serializable {
    /**
     * 主键id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long id;

    /**
     * 父节点
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long parentId;

    /**
     * 部门code（用以简化查询）
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String depCode;

    /**
     * 部门名称
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String depName;

    /**
     * 部门描述
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String depDesc;

    /**
     * 是否有叶子节点 0 有 1 没有
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Byte depIsleaf;

    /**
     * 删除标识 0 否 1 是
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Boolean isDel;

    /**
     * 创建时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date createTime;

    /**
     * 更新时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date updateTime;

    private List<CrmDep> children;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_dep
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_dep.id
     *
     * @return the value of crm_dep.id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_dep.id
     *
     * @param id the value for crm_dep.id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_dep.parent_id
     *
     * @return the value of crm_dep.parent_id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_dep.parent_id
     *
     * @param parentId the value for crm_dep.parent_id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_dep.dep_code
     *
     * @return the value of crm_dep.dep_code
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_dep.dep_code
     *
     * @param depCode the value for crm_dep.dep_code
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode == null ? null : depCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_dep.dep_name
     *
     * @return the value of crm_dep.dep_name
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_dep.dep_name
     *
     * @param depName the value for crm_dep.dep_name
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_dep.dep_desc
     *
     * @return the value of crm_dep.dep_desc
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getDepDesc() {
        return depDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_dep.dep_desc
     *
     * @param depDesc the value for crm_dep.dep_desc
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setDepDesc(String depDesc) {
        this.depDesc = depDesc == null ? null : depDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_dep.dep_isleaf
     *
     * @return the value of crm_dep.dep_isleaf
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Byte getDepIsleaf() {
        return depIsleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_dep.dep_isleaf
     *
     * @param depIsleaf the value for crm_dep.dep_isleaf
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setDepIsleaf(Byte depIsleaf) {
        this.depIsleaf = depIsleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_dep.is_del
     *
     * @return the value of crm_dep.is_del
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_dep.is_del
     *
     * @param isDel the value for crm_dep.is_del
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_dep.create_time
     *
     * @return the value of crm_dep.create_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_dep.create_time
     *
     * @param createTime the value for crm_dep.create_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_dep.update_time
     *
     * @return the value of crm_dep.update_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_dep.update_time
     *
     * @param updateTime the value for crm_dep.update_time
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public List<CrmDep> getChildren() {
		return children;
	}

	public void setChildren(List<CrmDep> children) {
		this.children = children;
	}
    
    
}