package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class CrmGathering extends BaseModel implements Serializable {
    /**
     * 主键id
     *
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    private Long id;

    /**
     * 合同id
     *
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    private Long contId;

    /**
     * 到款金额
     *
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    private Long gathMoney;

    /**
     * 收款日期
     *
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    private Date gathDate;

    /**
     * 登记人ID
     *
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    private Long registerId;

    /**
     * 登记人姓名
     *
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    private String registerName;

    /**
     * 删除标识
     *
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    private Boolean isDel;

    /**
     * 创建时间
     *
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    private Date createTime;

    /**
     * 更新时间
     *
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_gathering
     *
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    private static final long serialVersionUID = 1L;


    //虚属性
    private String custName;//客户名称

    private String owerName;//归属人

    private Long owner;//归属人ID

    private String contNumber;//合同编号

    private Byte contType;//合同类型
    private String contTypeStr;//合同类型

    private Date gathTimestart;

    private Date gathTimeend;

    private Long clueId;//线索ID

    private Byte accStatus;//账号开通状态


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_gathering.id
     *
     * @return the value of crm_gathering.id
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_gathering.id
     *
     * @param id the value for crm_gathering.id
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_gathering.cont_id
     *
     * @return the value of crm_gathering.cont_id
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public Long getContId() {
        return contId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_gathering.cont_id
     *
     * @param contId the value for crm_gathering.cont_id
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public void setContId(Long contId) {
        this.contId = contId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_gathering.gath_money
     *
     * @return the value of crm_gathering.gath_money
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public Long getGathMoney() {
        return gathMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_gathering.gath_money
     *
     * @param gathMoney the value for crm_gathering.gath_money
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public void setGathMoney(Long gathMoney) {
        this.gathMoney = gathMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_gathering.gath_date
     *
     * @return the value of crm_gathering.gath_date
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public Date getGathDate() {
        return gathDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_gathering.gath_date
     *
     * @param gathDate the value for crm_gathering.gath_date
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public void setGathDate(Date gathDate) {
        this.gathDate = gathDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_gathering.register_id
     *
     * @return the value of crm_gathering.register_id
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public Long getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_gathering.register_id
     *
     * @param registerId the value for crm_gathering.register_id
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public void setRegisterId(Long registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_gathering.register_name
     *
     * @return the value of crm_gathering.register_name
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public String getRegisterName() {
        return registerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_gathering.register_name
     *
     * @param registerName the value for crm_gathering.register_name
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public void setRegisterName(String registerName) {
        this.registerName = registerName == null ? null : registerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_gathering.is_del
     *
     * @return the value of crm_gathering.is_del
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_gathering.is_del
     *
     * @param isDel the value for crm_gathering.is_del
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_gathering.create_time
     *
     * @return the value of crm_gathering.create_time
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_gathering.create_time
     *
     * @param createTime the value for crm_gathering.create_time
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_gathering.update_time
     *
     * @return the value of crm_gathering.update_time
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_gathering.update_time
     *
     * @param updateTime the value for crm_gathering.update_time
     * @mbggenerated Wed Aug 05 14:41:06 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getCustName() {
        return custName;
    }

    public void setCustName(String custName) {
        this.custName = custName;
    }

    public String getOwerName() {
        return owerName;
    }

    public void setOwerName(String owerName) {
        this.owerName = owerName;
    }

    public String getContNumber() {
        return contNumber;
    }

    public void setContNumber(String contNumber) {
        this.contNumber = contNumber;
    }

    public Byte getContType() {
        return contType;
    }

    public void setContType(Byte contType) {
        this.contType = contType;
    }

    public Date getGathTimestart() {
        return gathTimestart;
    }

    public void setGathTimestart(Date gathTimestart) {
        this.gathTimestart = gathTimestart;
    }

    public Date getGathTimeend() {
        return gathTimeend;
    }

    public void setGathTimeend(Date gathTimeend) {
        this.gathTimeend = gathTimeend;
    }

    public Long getClueId() {
        return clueId;
    }

    public void setClueId(Long clueId) {
        this.clueId = clueId;
    }

    public Long getOwner() {
        return owner;
    }

    public void setOwner(Long owner) {
        this.owner = owner;
    }

    public String getContTypeStr() {
        return contTypeStr;
    }

    public void setContTypeStr(String contTypeStr) {
        this.contTypeStr = contTypeStr;
    }

    public Byte getAccStatus() {
        return accStatus;
    }

    public void setAccStatus(Byte accStatus) {
        this.accStatus = accStatus;
    }

}