package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class CrmProduct extends BaseModel implements Serializable {
    /**
     * id
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long id;

    /**
     * 产品名称
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private String productName;

    /**
     * 产品状态
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Byte productStatus;

    /**
     * 产品类型
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Byte productType;

    /**
     * 产品价格
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Long productPrice;

    /**
     * 删除标识
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Boolean isDel;

    /**
     * 创建时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date createTime;

    /**
     * 更新时间
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private Date updateTime;

    /**
     * 标准版套餐名称
     */
    private String versName;

    /**
     * 产品关联的套餐集合
     */
    private List<CrmProductVersion> versionList;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_product
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    private static final long serialVersionUID = 1L;


    public String getVersName() {
        return versName;
    }

    public void setVersName(String versName) {
        this.versName = versName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_product.id
     *
     * @return the value of crm_product.id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_product.id
     *
     * @param id the value for crm_product.id
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_product.product_name
     *
     * @return the value of crm_product.product_name
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_product.product_name
     *
     * @param productName the value for crm_product.product_name
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_product.product_status
     *
     * @return the value of crm_product.product_status
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Byte getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_product.product_status
     *
     * @param productStatus the value for crm_product.product_status
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setProductStatus(Byte productStatus) {
        this.productStatus = productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_product.product_type
     *
     * @return the value of crm_product.product_type
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Byte getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_product.product_type
     *
     * @param productType the value for crm_product.product_type
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setProductType(Byte productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_product.product_price
     *
     * @return the value of crm_product.product_price
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Long getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_product.product_price
     *
     * @param productPrice the value for crm_product.product_price
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setProductPrice(Long productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_product.is_del
     *
     * @return the value of crm_product.is_del
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_product.is_del
     *
     * @param isDel the value for crm_product.is_del
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_product.create_time
     *
     * @return the value of crm_product.create_time
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_product.create_time
     *
     * @param createTime the value for crm_product.create_time
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_product.update_time
     *
     * @return the value of crm_product.update_time
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_product.update_time
     *
     * @param updateTime the value for crm_product.update_time
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }


    public List<CrmProductVersion> getVersionList() {
        return versionList;
    }

    public void setVersionList(List<CrmProductVersion> versionList) {
        this.versionList = versionList;
    }

    @Override
    public String toString() {
        return "CrmProduct{" +
                "id=" + id +
                ", productName='" + productName + '\'' +
                ", productStatus=" + productStatus +
                ", productType=" + productType +
                ", productPrice=" + productPrice +
                ", isDel=" + isDel +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                '}';
    }
}