package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class CrmRoleAuth extends BaseModel implements Serializable {
    /**
     * 主键id
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private Long id;

    /**
     * 角色id
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private Long roleId;

    /**
     * 权限id
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private Long authId;

    /**
     * 删除标识 0 否 1 是
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private Boolean isDel;

    /**
     * 创建时间
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private Date createTime;

    /**
     * 更新时间
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private Date updateTime;

    private List<CrmAuth> authList;
    
    private String authName;
    

	public String getAuthName() {
		return authName;
	}

	public void setAuthName(String authName) {
		this.authName = authName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_role_auth
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role_auth.id
     *
     * @return the value of crm_role_auth.id
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role_auth.id
     *
     * @param id the value for crm_role_auth.id
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    

	public List<CrmAuth> getAuthList() {
		return authList;
	}

	public void setAuthList(List<CrmAuth> authList) {
		this.authList = authList;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role_auth.role_id
     *
     * @return the value of crm_role_auth.role_id
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role_auth.role_id
     *
     * @param roleId the value for crm_role_auth.role_id
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role_auth.auth_id
     *
     * @return the value of crm_role_auth.auth_id
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Long getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role_auth.auth_id
     *
     * @param authId the value for crm_role_auth.auth_id
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setAuthId(Long authId) {
        this.authId = authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role_auth.is_del
     *
     * @return the value of crm_role_auth.is_del
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role_auth.is_del
     *
     * @param isDel the value for crm_role_auth.is_del
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role_auth.create_time
     *
     * @return the value of crm_role_auth.create_time
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role_auth.create_time
     *
     * @param createTime the value for crm_role_auth.create_time
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role_auth.update_time
     *
     * @return the value of crm_role_auth.update_time
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role_auth.update_time
     *
     * @param updateTime the value for crm_role_auth.update_time
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}