package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class CrmRole extends BaseModel implements Serializable {
    /**
     * 主键id
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private Long id;

    /**
     * 角色code
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private Integer roleCode;

    /**
     * 角色名称
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private String roleName;

    /**
     * 角色描述
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private String roleDesc;

    /**
     * 角色类型 0 超级管理员 1 普通管理员
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private Byte roleType;

    /**
     * 删除标识 0 否 1 是
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private Boolean isDel;

    /**
     * 创建时间
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private Date createTime;

    /**
     * 更新时间
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private Date updateTime;

    private long[] authIdArray;


    private List<CrmRoleAuth> authRoleList;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_role
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private static final long serialVersionUID = 1L;


    public long[] getAuthIdArray() {
        return authIdArray;
    }

    public void setAuthIdArray(long[] authIdArray) {
        this.authIdArray = authIdArray;
    }


    public List<CrmRoleAuth> getAuthRoleList() {
        return authRoleList;
    }

    public void setAuthRoleList(List<CrmRoleAuth> authRoleList) {
        this.authRoleList = authRoleList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role.id
     *
     * @return the value of crm_role.id
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role.id
     *
     * @param id the value for crm_role.id
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role.role_code
     *
     * @return the value of crm_role.role_code
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Integer getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role.role_code
     *
     * @param roleCode the value for crm_role.role_code
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setRoleCode(Integer roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role.role_name
     *
     * @return the value of crm_role.role_name
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role.role_name
     *
     * @param roleName the value for crm_role.role_name
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role.role_desc
     *
     * @return the value of crm_role.role_desc
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role.role_desc
     *
     * @param roleDesc the value for crm_role.role_desc
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role.role_type
     *
     * @return the value of crm_role.role_type
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Byte getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role.role_type
     *
     * @param roleType the value for crm_role.role_type
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setRoleType(Byte roleType) {
        this.roleType = roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role.is_del
     *
     * @return the value of crm_role.is_del
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role.is_del
     *
     * @param isDel the value for crm_role.is_del
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role.create_time
     *
     * @return the value of crm_role.create_time
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role.create_time
     *
     * @param createTime the value for crm_role.create_time
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role.update_time
     *
     * @return the value of crm_role.update_time
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role.update_time
     *
     * @param updateTime the value for crm_role.update_time
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}