package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class Districts extends BaseModel implements Serializable {
    private Integer id;

    private String name;

    private String pinyin;

    private Integer cityId;

    private Integer sort;

    private Date createdAt;

    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table districts
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column districts.id
     *
     * @return the value of districts.id
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column districts.id
     *
     * @param id the value for districts.id
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column districts.name
     *
     * @return the value of districts.name
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column districts.name
     *
     * @param name the value for districts.name
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column districts.pinyin
     *
     * @return the value of districts.pinyin
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column districts.pinyin
     *
     * @param pinyin the value for districts.pinyin
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column districts.city_id
     *
     * @return the value of districts.city_id
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column districts.city_id
     *
     * @param cityId the value for districts.city_id
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column districts.sort
     *
     * @return the value of districts.sort
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column districts.sort
     *
     * @param sort the value for districts.sort
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column districts.created_at
     *
     * @return the value of districts.created_at
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column districts.created_at
     *
     * @param createdAt the value for districts.created_at
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column districts.updated_at
     *
     * @return the value of districts.updated_at
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column districts.updated_at
     *
     * @param updatedAt the value for districts.updated_at
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}