package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class Provinces extends BaseModel implements Serializable {
    private Integer id;

    private String name;

    private String pinyin;

    private Integer sort;

    private Date createdAt;

    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table provinces
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provinces.id
     *
     * @return the value of provinces.id
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provinces.id
     *
     * @param id the value for provinces.id
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provinces.name
     *
     * @return the value of provinces.name
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provinces.name
     *
     * @param name the value for provinces.name
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provinces.pinyin
     *
     * @return the value of provinces.pinyin
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provinces.pinyin
     *
     * @param pinyin the value for provinces.pinyin
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provinces.sort
     *
     * @return the value of provinces.sort
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provinces.sort
     *
     * @param sort the value for provinces.sort
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provinces.created_at
     *
     * @return the value of provinces.created_at
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provinces.created_at
     *
     * @param createdAt the value for provinces.created_at
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provinces.updated_at
     *
     * @return the value of provinces.updated_at
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provinces.updated_at
     *
     * @param updatedAt the value for provinces.updated_at
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}