package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class VegeSysCompany extends BaseModel implements Serializable {
    /**
     * 编号 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer id;

    /**
     * 创建时间 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Date createDate;

    /**
     * 修改时间 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Date modifyDate;

    /**
     * 创建人 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String creator;

    /**
     * 修改人 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String modifier;

    /**
     * 是否有效 1代表有效,0代表失效已删除
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Byte isValid;

    /**
     * 公司名称 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String companyName;

    /**
     * 公司描述 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String companyDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vege_sys_company
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_company.id
     *
     * @return the value of vege_sys_company.id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_company.id
     *
     * @param id the value for vege_sys_company.id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_company.create_date
     *
     * @return the value of vege_sys_company.create_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_company.create_date
     *
     * @param createDate the value for vege_sys_company.create_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_company.modify_date
     *
     * @return the value of vege_sys_company.modify_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_company.modify_date
     *
     * @param modifyDate the value for vege_sys_company.modify_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_company.creator
     *
     * @return the value of vege_sys_company.creator
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_company.creator
     *
     * @param creator the value for vege_sys_company.creator
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_company.modifier
     *
     * @return the value of vege_sys_company.modifier
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_company.modifier
     *
     * @param modifier the value for vege_sys_company.modifier
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_company.is_valid
     *
     * @return the value of vege_sys_company.is_valid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_company.is_valid
     *
     * @param isValid the value for vege_sys_company.is_valid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_company.company_name
     *
     * @return the value of vege_sys_company.company_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_company.company_name
     *
     * @param companyName the value for vege_sys_company.company_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_company.company_desc
     *
     * @return the value of vege_sys_company.company_desc
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getCompanyDesc() {
        return companyDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_company.company_desc
     *
     * @param companyDesc the value for vege_sys_company.company_desc
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCompanyDesc(String companyDesc) {
        this.companyDesc = companyDesc == null ? null : companyDesc.trim();
    }
}