package com.vcooline.crm.common.model

class VegeProdect extends BaseModel implements Serializable {
    /**
     * 主键 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Integer id

    /**
     * 商品分类标识 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Integer categoryId

    /**
     * 商品分类标识 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String caregoryName

    /**
     * 商品编码 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String number

    /**
     * 商品名称 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String name

    /**
     * 商品条码 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String barcode

    /**
     * 单位 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String unit

    /**
     * 价格 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Double price

    /**
     * 是否称重 false 代表不需要，true 代表需要
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String allowWeigh

    /**
     * 店铺标识 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Integer shopId

    /**
     * 店铺名称 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String shopName

    /**
     * 卖方标识 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String sellerId

    /**
     * 卖方名称 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String sellerName

    /**
     * 创建时间 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Date creationTime

    /**
     * 更新时间 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Date updateTime

    /**
     * 产地 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String placeOfOrigin

    /**
     * 规格 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String specification

    /**
     * 商品等级 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String grade

    /**
     * 促销标记 0代表不促销
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Byte promotionFlag

    /**
     * 促销价格 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Double promotionPrice

    /**
     * 促销开始时间 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Date promoTimeFrom

    /**
     * 促销结束时间 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Date promoTimeTo

    /**
     * 追溯码URL 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String traceCode

    /**
     * 产品图 多图片用“|”分割
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String photo

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vege_product
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private static final long serialVersionUID = 1L

    Integer getId() {
        return id
    }

    void setId(Integer id) {
        this.id = id
    }

    Integer getCategoryId() {
        return categoryId
    }

    void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId
    }

    String getCaregoryName() {
        return caregoryName
    }

    void setCaregoryName(String caregoryName) {
        this.caregoryName = caregoryName
    }

    String getNumber() {
        return number
    }

    void setNumber(String number) {
        this.number = number
    }

    String getName() {
        return name
    }

    void setName(String name) {
        this.name = name
    }

    String getBarcode() {
        return barcode
    }

    void setBarcode(String barcode) {
        this.barcode = barcode
    }

    String getUnit() {
        return unit
    }

    void setUnit(String unit) {
        this.unit = unit
    }

    Double getPrice() {
        return price
    }

    void setPrice(Double price) {
        this.price = price
    }

    String getAllowWeigh() {
        return allowWeigh
    }

    void setAllowWeigh(String allowWeigh) {
        this.allowWeigh = allowWeigh
    }

    Integer getShopId() {
        return shopId
    }

    void setShopId(Integer shopId) {
        this.shopId = shopId
    }

    String getShopName() {
        return shopName
    }

    void setShopName(String shopName) {
        this.shopName = shopName
    }

    String getSellerId() {
        return sellerId
    }

    void setSellerId(String sellerId) {
        this.sellerId = sellerId
    }

    String getSellerName() {
        return sellerName
    }

    void setSellerName(String sellerName) {
        this.sellerName = sellerName
    }

    Date getCreationTime() {
        return creationTime
    }

    void setCreationTime(Date creationTime) {
        this.creationTime = creationTime
    }

    Date getUpdateTime() {
        return updateTime
    }

    void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime
    }

    String getPlaceOfOrigin() {
        return placeOfOrigin
    }

    void setPlaceOfOrigin(String placeOfOrigin) {
        this.placeOfOrigin = placeOfOrigin
    }

    String getSpecification() {
        return specification
    }

    void setSpecification(String specification) {
        this.specification = specification
    }

    String getGrade() {
        return grade
    }

    void setGrade(String grade) {
        this.grade = grade
    }

    Byte getPromotionFlag() {
        return promotionFlag
    }

    void setPromotionFlag(Byte promotionFlag) {
        this.promotionFlag = promotionFlag
    }

    Double getPromotionPrice() {
        return promotionPrice
    }

    void setPromotionPrice(Double promotionPrice) {
        this.promotionPrice = promotionPrice
    }

    Date getPromoTimeFrom() {
        return promoTimeFrom
    }

    void setPromoTimeFrom(Date promoTimeFrom) {
        this.promoTimeFrom = promoTimeFrom
    }

    Date getPromoTimeTo() {
        return promoTimeTo
    }

    void setPromoTimeTo(Date promoTimeTo) {
        this.promoTimeTo = promoTimeTo
    }

    String getTraceCode() {
        return traceCode
    }

    void setTraceCode(String traceCode) {
        this.traceCode = traceCode
    }

    String getPhoto() {
        return photo
    }

    void setPhoto(String photo) {
        this.photo = photo
    }

    @Override
    public String toString() {
        return "VegeProdect{" +
                "id=" + id +
                ", categoryId=" + categoryId +
                ", caregoryName='" + caregoryName + '\'' +
                ", number='" + number + '\'' +
                ", name='" + name + '\'' +
                ", barcode='" + barcode + '\'' +
                ", unit='" + unit + '\'' +
                ", price=" + price +
                ", allowWeigh='" + allowWeigh + '\'' +
                ", shopId=" + shopId +
                ", shopName='" + shopName + '\'' +
                ", sellerId='" + sellerId + '\'' +
                ", sellerName='" + sellerName + '\'' +
                ", creationTime=" + creationTime +
                ", updateTime=" + updateTime +
                ", placeOfOrigin='" + placeOfOrigin + '\'' +
                ", specification='" + specification + '\'' +
                ", grade='" + grade + '\'' +
                ", promotionFlag=" + promotionFlag +
                ", promotionPrice=" + promotionPrice +
                ", promoTimeFrom=" + promoTimeFrom +
                ", promoTimeTo=" + promoTimeTo +
                ", traceCode='" + traceCode + '\'' +
                ", photo='" + photo + '\'' +
                '}';
    }
}