package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class VegeProdect extends BaseModel implements Serializable {
    /**
     * 主键 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Integer id;

    /**
     * 商品分类标识 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Integer categoryId;

    /**
     * 商品分类标识 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String caregoryName;

    /**
     * 商品编码 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String number;

    /**
     * 商品名称 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String name;

    /**
     * 商品条码 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String barcode;

    /**
     * 单位 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String unit;

    /**
     * 价格 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Double price;

    /**
     * 是否称重 false 代表不需要，true 代表需要
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String allowWeigh;

    /**
     * 店铺标识 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Integer shopId;

    /**
     * 店铺名称 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String shopName;

    /**
     * 卖方标识 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String sellerId;

    /**
     * 卖方名称 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String sellerName;

    /**
     * 创建时间 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Date creationTime;

    /**
     * 更新时间 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Date updateTime;

    /**
     * 产地 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String placeOfOrigin;

    /**
     * 规格 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String specification;

    /**
     * 商品等级 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String grade;

    /**
     * 促销标记 0代表不促销
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Byte promotionFlag;

    /**
     * 促销价格 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Double promotionPrice;

    /**
     * 促销开始时间 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Date promoTimeFrom;

    /**
     * 促销结束时间 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private Date promoTimeTo;

    /**
     * 追溯码URL 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String traceCode;

    /**
     * 产品图 多图片用“|”分割
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vege_product
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.id
     *
     * @return the value of vege_product.id
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.id
     *
     * @param id the value for vege_product.id
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.category_id
     *
     * @return the value of vege_product.category_id
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.category_id
     *
     * @param categoryId the value for vege_product.category_id
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.caregory_name
     *
     * @return the value of vege_product.caregory_name
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public String getCaregoryName() {
        return caregoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.caregory_name
     *
     * @param caregoryName the value for vege_product.caregory_name
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setCaregoryName(String caregoryName) {
        this.caregoryName = caregoryName == null ? null : caregoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.number
     *
     * @return the value of vege_product.number
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.number
     *
     * @param number the value for vege_product.number
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.name
     *
     * @return the value of vege_product.name
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.name
     *
     * @param name the value for vege_product.name
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.barcode
     *
     * @return the value of vege_product.barcode
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.barcode
     *
     * @param barcode the value for vege_product.barcode
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.unit
     *
     * @return the value of vege_product.unit
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.unit
     *
     * @param unit the value for vege_product.unit
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.price
     *
     * @return the value of vege_product.price
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.price
     *
     * @param price the value for vege_product.price
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.allow_weigh
     *
     * @return the value of vege_product.allow_weigh
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public String getAllowWeigh() {
        return allowWeigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.allow_weigh
     *
     * @param allowWeigh the value for vege_product.allow_weigh
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setAllowWeigh(String allowWeigh) {
        this.allowWeigh = allowWeigh == null ? null : allowWeigh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.shop_id
     *
     * @return the value of vege_product.shop_id
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.shop_id
     *
     * @param shopId the value for vege_product.shop_id
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.shop_name
     *
     * @return the value of vege_product.shop_name
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.shop_name
     *
     * @param shopName the value for vege_product.shop_name
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.seller_id
     *
     * @return the value of vege_product.seller_id
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.seller_id
     *
     * @param sellerId the value for vege_product.seller_id
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId == null ? null : sellerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.seller_name
     *
     * @return the value of vege_product.seller_name
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public String getSellerName() {
        return sellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.seller_name
     *
     * @param sellerName the value for vege_product.seller_name
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName == null ? null : sellerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.creation_time
     *
     * @return the value of vege_product.creation_time
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.creation_time
     *
     * @param creationTime the value for vege_product.creation_time
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.update_time
     *
     * @return the value of vege_product.update_time
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.update_time
     *
     * @param updateTime the value for vege_product.update_time
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.place_of_origin
     *
     * @return the value of vege_product.place_of_origin
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public String getPlaceOfOrigin() {
        return placeOfOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.place_of_origin
     *
     * @param placeOfOrigin the value for vege_product.place_of_origin
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setPlaceOfOrigin(String placeOfOrigin) {
        this.placeOfOrigin = placeOfOrigin == null ? null : placeOfOrigin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.specification
     *
     * @return the value of vege_product.specification
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.specification
     *
     * @param specification the value for vege_product.specification
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.grade
     *
     * @return the value of vege_product.grade
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.grade
     *
     * @param grade the value for vege_product.grade
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.promotion_flag
     *
     * @return the value of vege_product.promotion_flag
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public Byte getPromotionFlag() {
        return promotionFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.promotion_flag
     *
     * @param promotionFlag the value for vege_product.promotion_flag
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setPromotionFlag(Byte promotionFlag) {
        this.promotionFlag = promotionFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.promotion_price
     *
     * @return the value of vege_product.promotion_price
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public Double getPromotionPrice() {
        return promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.promotion_price
     *
     * @param promotionPrice the value for vege_product.promotion_price
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setPromotionPrice(Double promotionPrice) {
        this.promotionPrice = promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.promo_time_from
     *
     * @return the value of vege_product.promo_time_from
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public Date getPromoTimeFrom() {
        return promoTimeFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.promo_time_from
     *
     * @param promoTimeFrom the value for vege_product.promo_time_from
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setPromoTimeFrom(Date promoTimeFrom) {
        this.promoTimeFrom = promoTimeFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.promo_time_to
     *
     * @return the value of vege_product.promo_time_to
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public Date getPromoTimeTo() {
        return promoTimeTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.promo_time_to
     *
     * @param promoTimeTo the value for vege_product.promo_time_to
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setPromoTimeTo(Date promoTimeTo) {
        this.promoTimeTo = promoTimeTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.trace_code
     *
     * @return the value of vege_product.trace_code
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public String getTraceCode() {
        return traceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.trace_code
     *
     * @param traceCode the value for vege_product.trace_code
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setTraceCode(String traceCode) {
        this.traceCode = traceCode == null ? null : traceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.photo
     *
     * @return the value of vege_product.photo
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.photo
     *
     * @param photo the value for vege_product.photo
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }
}