package com.vcooline.crm.common.model;

import java.io.Serializable;

public class VegeProdectWithBLOBs extends VegeProdect implements Serializable {
    /**
     * 手机详情 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String mobileDesc;

    /**
     * pc端详情 
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private String pcDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vege_product
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.mobile_desc
     *
     * @return the value of vege_product.mobile_desc
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public String getMobileDesc() {
        return mobileDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.mobile_desc
     *
     * @param mobileDesc the value for vege_product.mobile_desc
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setMobileDesc(String mobileDesc) {
        this.mobileDesc = mobileDesc == null ? null : mobileDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_product.pc_desc
     *
     * @return the value of vege_product.pc_desc
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public String getPcDesc() {
        return pcDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_product.pc_desc
     *
     * @param pcDesc the value for vege_product.pc_desc
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    public void setPcDesc(String pcDesc) {
        this.pcDesc = pcDesc == null ? null : pcDesc.trim();
    }
}