package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class VegeSysUser extends BaseModel implements Serializable {
    /**
     * 编号 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer id;

    /**
     * 创建时间 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Date createDate;

    /**
     * 修改时间 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Date modifyDate;

    /**
     * 创建人 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String creator;

    /**
     * 修改人 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String modifier;

    /**
     * 是否有效 1代表有效,0代表失效已删除
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Byte isValid;

    /**
     * 用户登录名 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String userName;

    /**
     * 用户密码 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String password;

    /**
     * 用户昵称 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String nickName;

    /**
     * 用户真实姓名 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String trueName;

    /**
     * 性别 1男 2女  0未知
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Byte sex;

    /**
     * 联系电话 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String phone;

    /**
     * 邮箱 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String email;

    /**
     * 头像 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String headImg;

    /**
     * 系统公司编号 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer sysCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vege_sys_user
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_user.id
     *
     * @return the value of vege_sys_user.id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_user.id
     *
     * @param id the value for vege_sys_user.id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_user.create_date
     *
     * @return the value of vege_sys_user.create_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_user.create_date
     *
     * @param createDate the value for vege_sys_user.create_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_user.modify_date
     *
     * @return the value of vege_sys_user.modify_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_user.modify_date
     *
     * @param modifyDate the value for vege_sys_user.modify_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_user.creator
     *
     * @return the value of vege_sys_user.creator
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_user.creator
     *
     * @param creator the value for vege_sys_user.creator
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_user.modifier
     *
     * @return the value of vege_sys_user.modifier
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_user.modifier
     *
     * @param modifier the value for vege_sys_user.modifier
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_user.is_valid
     *
     * @return the value of vege_sys_user.is_valid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_user.is_valid
     *
     * @param isValid the value for vege_sys_user.is_valid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_user.user_name
     *
     * @return the value of vege_sys_user.user_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_user.user_name
     *
     * @param userName the value for vege_sys_user.user_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_user.password
     *
     * @return the value of vege_sys_user.password
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_user.password
     *
     * @param password the value for vege_sys_user.password
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_user.nick_name
     *
     * @return the value of vege_sys_user.nick_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_user.nick_name
     *
     * @param nickName the value for vege_sys_user.nick_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_user.true_name
     *
     * @return the value of vege_sys_user.true_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_user.true_name
     *
     * @param trueName the value for vege_sys_user.true_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName == null ? null : trueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_user.sex
     *
     * @return the value of vege_sys_user.sex
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_user.sex
     *
     * @param sex the value for vege_sys_user.sex
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_user.phone
     *
     * @return the value of vege_sys_user.phone
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_user.phone
     *
     * @param phone the value for vege_sys_user.phone
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_user.email
     *
     * @return the value of vege_sys_user.email
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_user.email
     *
     * @param email the value for vege_sys_user.email
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_user.head_img
     *
     * @return the value of vege_sys_user.head_img
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_user.head_img
     *
     * @param headImg the value for vege_sys_user.head_img
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_sys_user.sys_company_id
     *
     * @return the value of vege_sys_user.sys_company_id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getSysCompanyId() {
        return sysCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_sys_user.sys_company_id
     *
     * @param sysCompanyId the value for vege_sys_user.sys_company_id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setSysCompanyId(Integer sysCompanyId) {
        this.sysCompanyId = sysCompanyId;
    }
}