package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class VegeRaffle extends BaseModel implements Serializable {
    /**
     * 编号 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer id;

    /**
     * 创建时间 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Date createDate;

    /**
     * 修改时间 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Date modifyDate;

    /**
     * 创建人 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String creator;

    /**
     * 修改人 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String modifier;

    /**
     * 是否有效 1代表有效,0代表失效已删除
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Byte isValid;

    /**
     * 奖品名称 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String raffleName;

    /**
     * 奖品图片 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String rafflePhoto;

    /**
     * 系统公司编号 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer sysCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vege_raffle
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle.id
     *
     * @return the value of vege_raffle.id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle.id
     *
     * @param id the value for vege_raffle.id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle.create_date
     *
     * @return the value of vege_raffle.create_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle.create_date
     *
     * @param createDate the value for vege_raffle.create_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle.modify_date
     *
     * @return the value of vege_raffle.modify_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle.modify_date
     *
     * @param modifyDate the value for vege_raffle.modify_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle.creator
     *
     * @return the value of vege_raffle.creator
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle.creator
     *
     * @param creator the value for vege_raffle.creator
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle.modifier
     *
     * @return the value of vege_raffle.modifier
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle.modifier
     *
     * @param modifier the value for vege_raffle.modifier
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle.is_valid
     *
     * @return the value of vege_raffle.is_valid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle.is_valid
     *
     * @param isValid the value for vege_raffle.is_valid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle.raffle_name
     *
     * @return the value of vege_raffle.raffle_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getRaffleName() {
        return raffleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle.raffle_name
     *
     * @param raffleName the value for vege_raffle.raffle_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setRaffleName(String raffleName) {
        this.raffleName = raffleName == null ? null : raffleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle.raffle_photo
     *
     * @return the value of vege_raffle.raffle_photo
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getRafflePhoto() {
        return rafflePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle.raffle_photo
     *
     * @param rafflePhoto the value for vege_raffle.raffle_photo
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setRafflePhoto(String rafflePhoto) {
        this.rafflePhoto = rafflePhoto == null ? null : rafflePhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle.sys_company_id
     *
     * @return the value of vege_raffle.sys_company_id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getSysCompanyId() {
        return sysCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle.sys_company_id
     *
     * @param sysCompanyId the value for vege_raffle.sys_company_id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setSysCompanyId(Integer sysCompanyId) {
        this.sysCompanyId = sysCompanyId;
    }
}