package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class VegePaymentRecord extends BaseModel implements Serializable {
    /**
     * 主键 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer id;

    /**
     * 创建时间 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Date createDate;

    /**
     * 修改时间 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Date modifyDate;

    /**
     * 创建人 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String creator;

    /**
     * 修改人 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String modifier;

    /**
     * 缴费类型 1:水费2：电费3：燃气费
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer type;

    /**
     * 用户编号 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String userNumber;

    /**
     * 缴费单位 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String companyName;

    /**
     * 缴费金额 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Double payAmount;

    /**
     * 支付方式 1：支付宝（默认）
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer payMode;

    /**
     * 支付帐号 支付帐号
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String payAccounts;

    /**
     * 是否有效 1代表有效,0代表失效已删除
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Byte isValid;

    /**
     * 系统公司编号 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer sysCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vege_payment_record
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_payment_record.id
     *
     * @return the value of vege_payment_record.id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_payment_record.id
     *
     * @param id the value for vege_payment_record.id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_payment_record.create_date
     *
     * @return the value of vege_payment_record.create_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_payment_record.create_date
     *
     * @param createDate the value for vege_payment_record.create_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_payment_record.modify_date
     *
     * @return the value of vege_payment_record.modify_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_payment_record.modify_date
     *
     * @param modifyDate the value for vege_payment_record.modify_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_payment_record.creator
     *
     * @return the value of vege_payment_record.creator
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_payment_record.creator
     *
     * @param creator the value for vege_payment_record.creator
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_payment_record.modifier
     *
     * @return the value of vege_payment_record.modifier
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_payment_record.modifier
     *
     * @param modifier the value for vege_payment_record.modifier
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_payment_record.type
     *
     * @return the value of vege_payment_record.type
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_payment_record.type
     *
     * @param type the value for vege_payment_record.type
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_payment_record.user_number
     *
     * @return the value of vege_payment_record.user_number
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_payment_record.user_number
     *
     * @param userNumber the value for vege_payment_record.user_number
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setUserNumber(String userNumber) {
        this.userNumber = userNumber == null ? null : userNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_payment_record.company_name
     *
     * @return the value of vege_payment_record.company_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_payment_record.company_name
     *
     * @param companyName the value for vege_payment_record.company_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_payment_record.pay_amount
     *
     * @return the value of vege_payment_record.pay_amount
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Double getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_payment_record.pay_amount
     *
     * @param payAmount the value for vege_payment_record.pay_amount
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setPayAmount(Double payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_payment_record.pay_mode
     *
     * @return the value of vege_payment_record.pay_mode
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getPayMode() {
        return payMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_payment_record.pay_mode
     *
     * @param payMode the value for vege_payment_record.pay_mode
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setPayMode(Integer payMode) {
        this.payMode = payMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_payment_record.pay_accounts
     *
     * @return the value of vege_payment_record.pay_accounts
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getPayAccounts() {
        return payAccounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_payment_record.pay_accounts
     *
     * @param payAccounts the value for vege_payment_record.pay_accounts
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setPayAccounts(String payAccounts) {
        this.payAccounts = payAccounts == null ? null : payAccounts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_payment_record.is_valid
     *
     * @return the value of vege_payment_record.is_valid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_payment_record.is_valid
     *
     * @param isValid the value for vege_payment_record.is_valid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_payment_record.sys_company_id
     *
     * @return the value of vege_payment_record.sys_company_id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getSysCompanyId() {
        return sysCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_payment_record.sys_company_id
     *
     * @param sysCompanyId the value for vege_payment_record.sys_company_id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setSysCompanyId(Integer sysCompanyId) {
        this.sysCompanyId = sysCompanyId;
    }
}