package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class VegeVendorExt extends BaseModel implements Serializable {
    /**
     * 编号 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer id;

    /**
     * 创建时间 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Date createDate;

    /**
     * 修改时间 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Date modifyDate;

    /**
     * 创建人 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String creator;

    /**
     * 修改人 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String modifier;

    /**
     * 是否有效 1代表有效,0代表失效已删除
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Byte isValid;

    /**
     * 名称 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String attrName;

    /**
     * 代码 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String attrCode;

    /**
     * 排序 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer orderNum;

    /**
     * 数据类型 1.文本
2.数值
3.日期
4.布尔
5.长文本
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer dataType;

    /**
     * 数据值 多值用|分割
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String attrValue;

    /**
     * 系统公司编号 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer sysCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vege_vendor_ext
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_vendor_ext.id
     *
     * @return the value of vege_vendor_ext.id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_vendor_ext.id
     *
     * @param id the value for vege_vendor_ext.id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_vendor_ext.create_date
     *
     * @return the value of vege_vendor_ext.create_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_vendor_ext.create_date
     *
     * @param createDate the value for vege_vendor_ext.create_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_vendor_ext.modify_date
     *
     * @return the value of vege_vendor_ext.modify_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_vendor_ext.modify_date
     *
     * @param modifyDate the value for vege_vendor_ext.modify_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_vendor_ext.creator
     *
     * @return the value of vege_vendor_ext.creator
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_vendor_ext.creator
     *
     * @param creator the value for vege_vendor_ext.creator
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_vendor_ext.modifier
     *
     * @return the value of vege_vendor_ext.modifier
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_vendor_ext.modifier
     *
     * @param modifier the value for vege_vendor_ext.modifier
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_vendor_ext.is_valid
     *
     * @return the value of vege_vendor_ext.is_valid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_vendor_ext.is_valid
     *
     * @param isValid the value for vege_vendor_ext.is_valid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_vendor_ext.attr_name
     *
     * @return the value of vege_vendor_ext.attr_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_vendor_ext.attr_name
     *
     * @param attrName the value for vege_vendor_ext.attr_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName == null ? null : attrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_vendor_ext.attr_code
     *
     * @return the value of vege_vendor_ext.attr_code
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getAttrCode() {
        return attrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_vendor_ext.attr_code
     *
     * @param attrCode the value for vege_vendor_ext.attr_code
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setAttrCode(String attrCode) {
        this.attrCode = attrCode == null ? null : attrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_vendor_ext.order_num
     *
     * @return the value of vege_vendor_ext.order_num
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_vendor_ext.order_num
     *
     * @param orderNum the value for vege_vendor_ext.order_num
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_vendor_ext.data_type
     *
     * @return the value of vege_vendor_ext.data_type
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_vendor_ext.data_type
     *
     * @param dataType the value for vege_vendor_ext.data_type
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_vendor_ext.attr_value
     *
     * @return the value of vege_vendor_ext.attr_value
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_vendor_ext.attr_value
     *
     * @param attrValue the value for vege_vendor_ext.attr_value
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue == null ? null : attrValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_vendor_ext.sys_company_id
     *
     * @return the value of vege_vendor_ext.sys_company_id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getSysCompanyId() {
        return sysCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_vendor_ext.sys_company_id
     *
     * @param sysCompanyId the value for vege_vendor_ext.sys_company_id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setSysCompanyId(Integer sysCompanyId) {
        this.sysCompanyId = sysCompanyId;
    }
}