package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class VegeRaffleActivity extends BaseModel implements Serializable {
    /**
     * 编号 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer id;

    /**
     * 创建时间 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Date createDate;

    /**
     * 修改时间 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Date modifyDate;

    /**
     * 创建人 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String creator;

    /**
     * 修改人 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String modifier;

    /**
     * 是否有效 1代表有效,0代表失效已删除
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Byte isValid;

    /**
     * 活动名称 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String activityName;

    /**
     * 中奖概率 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Double raffleProb;

    /**
     * 奖品编号 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer raffleId;

    /**
     * 系统公司编号 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer sysCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vege_raffle_activity
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle_activity.id
     *
     * @return the value of vege_raffle_activity.id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle_activity.id
     *
     * @param id the value for vege_raffle_activity.id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle_activity.create_date
     *
     * @return the value of vege_raffle_activity.create_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle_activity.create_date
     *
     * @param createDate the value for vege_raffle_activity.create_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle_activity.modify_date
     *
     * @return the value of vege_raffle_activity.modify_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle_activity.modify_date
     *
     * @param modifyDate the value for vege_raffle_activity.modify_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle_activity.creator
     *
     * @return the value of vege_raffle_activity.creator
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle_activity.creator
     *
     * @param creator the value for vege_raffle_activity.creator
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle_activity.modifier
     *
     * @return the value of vege_raffle_activity.modifier
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle_activity.modifier
     *
     * @param modifier the value for vege_raffle_activity.modifier
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle_activity.is_valid
     *
     * @return the value of vege_raffle_activity.is_valid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle_activity.is_valid
     *
     * @param isValid the value for vege_raffle_activity.is_valid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle_activity.activity_name
     *
     * @return the value of vege_raffle_activity.activity_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle_activity.activity_name
     *
     * @param activityName the value for vege_raffle_activity.activity_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle_activity.raffle_prob
     *
     * @return the value of vege_raffle_activity.raffle_prob
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Double getRaffleProb() {
        return raffleProb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle_activity.raffle_prob
     *
     * @param raffleProb the value for vege_raffle_activity.raffle_prob
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setRaffleProb(Double raffleProb) {
        this.raffleProb = raffleProb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle_activity.raffle_id
     *
     * @return the value of vege_raffle_activity.raffle_id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getRaffleId() {
        return raffleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle_activity.raffle_id
     *
     * @param raffleId the value for vege_raffle_activity.raffle_id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setRaffleId(Integer raffleId) {
        this.raffleId = raffleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_raffle_activity.sys_company_id
     *
     * @return the value of vege_raffle_activity.sys_company_id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getSysCompanyId() {
        return sysCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_raffle_activity.sys_company_id
     *
     * @param sysCompanyId the value for vege_raffle_activity.sys_company_id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setSysCompanyId(Integer sysCompanyId) {
        this.sysCompanyId = sysCompanyId;
    }
}