package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class VegeWorker extends BaseModel implements Serializable {
    /**
     * 编号 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer id;

    /**
     * 创建时间 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Date createDate;

    /**
     * 修改时间 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Date modifyDate;

    /**
     * 创建人 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String creator;

    /**
     * 修改人 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String modifier;

    /**
     * 是否有效 1代表有效,0代表失效已删除
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Byte isValid;

    /**
     * 性别 1男 2女  0未知
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Byte sex;

    /**
     * 出生日期 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Date birthday;

    /**
     * 职位 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String job;

    /**
     * 职位描述 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String jobDesc;

    /**
     * 头像 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String headImg;

    /**
     * 工号 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String jobNo;

    /**
     * 身份证 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String idCard;

    /**
     * 系统公司编号 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer sysCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vege_worker
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_worker.id
     *
     * @return the value of vege_worker.id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_worker.id
     *
     * @param id the value for vege_worker.id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_worker.create_date
     *
     * @return the value of vege_worker.create_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_worker.create_date
     *
     * @param createDate the value for vege_worker.create_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_worker.modify_date
     *
     * @return the value of vege_worker.modify_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_worker.modify_date
     *
     * @param modifyDate the value for vege_worker.modify_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_worker.creator
     *
     * @return the value of vege_worker.creator
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_worker.creator
     *
     * @param creator the value for vege_worker.creator
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_worker.modifier
     *
     * @return the value of vege_worker.modifier
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_worker.modifier
     *
     * @param modifier the value for vege_worker.modifier
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_worker.is_valid
     *
     * @return the value of vege_worker.is_valid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_worker.is_valid
     *
     * @param isValid the value for vege_worker.is_valid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_worker.sex
     *
     * @return the value of vege_worker.sex
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_worker.sex
     *
     * @param sex the value for vege_worker.sex
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_worker.birthday
     *
     * @return the value of vege_worker.birthday
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_worker.birthday
     *
     * @param birthday the value for vege_worker.birthday
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_worker.job
     *
     * @return the value of vege_worker.job
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_worker.job
     *
     * @param job the value for vege_worker.job
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_worker.job_desc
     *
     * @return the value of vege_worker.job_desc
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getJobDesc() {
        return jobDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_worker.job_desc
     *
     * @param jobDesc the value for vege_worker.job_desc
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setJobDesc(String jobDesc) {
        this.jobDesc = jobDesc == null ? null : jobDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_worker.head_img
     *
     * @return the value of vege_worker.head_img
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_worker.head_img
     *
     * @param headImg the value for vege_worker.head_img
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_worker.job_no
     *
     * @return the value of vege_worker.job_no
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getJobNo() {
        return jobNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_worker.job_no
     *
     * @param jobNo the value for vege_worker.job_no
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setJobNo(String jobNo) {
        this.jobNo = jobNo == null ? null : jobNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_worker.id_card
     *
     * @return the value of vege_worker.id_card
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_worker.id_card
     *
     * @param idCard the value for vege_worker.id_card
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_worker.sys_company_id
     *
     * @return the value of vege_worker.sys_company_id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getSysCompanyId() {
        return sysCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_worker.sys_company_id
     *
     * @param sysCompanyId the value for vege_worker.sys_company_id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setSysCompanyId(Integer sysCompanyId) {
        this.sysCompanyId = sysCompanyId;
    }
}