package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class VegeCategory extends BaseModel implements Serializable {
    /**
     * 主键 
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    private Integer id;

    /**
     * 创建时间 
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    private Date createDate;

    /**
     * 修改时间 
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    private Date modifyDate;

    /**
     * 创建人 
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    private String creator;

    /**
     * 修改人 
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    private String modifier;

    /**
     * 父分类 
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    private Integer parentId;

    /**
     * 分类名称 
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    private String categoryName;

    /**
     * 是否有效 1代表有效,0代表失效已删除
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    private Byte isValid;

    /**
     * 系统公司编号 
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    private Integer sysCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vege_category
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_category.id
     *
     * @return the value of vege_category.id
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_category.id
     *
     * @param id the value for vege_category.id
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_category.create_date
     *
     * @return the value of vege_category.create_date
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_category.create_date
     *
     * @param createDate the value for vege_category.create_date
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_category.modify_date
     *
     * @return the value of vege_category.modify_date
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_category.modify_date
     *
     * @param modifyDate the value for vege_category.modify_date
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_category.creator
     *
     * @return the value of vege_category.creator
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_category.creator
     *
     * @param creator the value for vege_category.creator
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_category.modifier
     *
     * @return the value of vege_category.modifier
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_category.modifier
     *
     * @param modifier the value for vege_category.modifier
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_category.parent_id
     *
     * @return the value of vege_category.parent_id
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_category.parent_id
     *
     * @param parentId the value for vege_category.parent_id
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_category.category_name
     *
     * @return the value of vege_category.category_name
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_category.category_name
     *
     * @param categoryName the value for vege_category.category_name
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_category.is_valid
     *
     * @return the value of vege_category.is_valid
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_category.is_valid
     *
     * @param isValid the value for vege_category.is_valid
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_category.sys_company_id
     *
     * @return the value of vege_category.sys_company_id
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public Integer getSysCompanyId() {
        return sysCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_category.sys_company_id
     *
     * @param sysCompanyId the value for vege_category.sys_company_id
     *
     * @mbggenerated Tue Oct 10 22:03:14 CST 2017
     */
    public void setSysCompanyId(Integer sysCompanyId) {
        this.sysCompanyId = sysCompanyId;
    }

    @Override
    public String toString() {
        return "VegeCategory{" +
                "id=" + id +
                ", createDate=" + createDate +
                ", modifyDate=" + modifyDate +
                ", creator='" + creator + '\'' +
                ", modifier='" + modifier + '\'' +
                ", parentId=" + parentId +
                ", categoryName='" + categoryName + '\'' +
                ", isValid=" + isValid +
                ", sysCompanyId=" + sysCompanyId +
                '}';
    }
}