package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class VegeMachine extends BaseModel implements Serializable {
    /**
     * 编号 
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    private Integer id;

    /**
     * 创建时间 
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    private Date createDate;

    /**
     * 机器编号 
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    private String machineCode;

    /**
     * 菜场编号 
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    private Integer companyId;

    /**
     * 菜场名字 
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    private String companyName;

    /**
     * 是否有效 1代表有效,0代表失效已删除
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    private Byte isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vege_machine
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_machine.id
     *
     * @return the value of vege_machine.id
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_machine.id
     *
     * @param id the value for vege_machine.id
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_machine.create_date
     *
     * @return the value of vege_machine.create_date
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_machine.create_date
     *
     * @param createDate the value for vege_machine.create_date
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_machine.machine_code
     *
     * @return the value of vege_machine.machine_code
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    public String getMachineCode() {
        return machineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_machine.machine_code
     *
     * @param machineCode the value for vege_machine.machine_code
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    public void setMachineCode(String machineCode) {
        this.machineCode = machineCode == null ? null : machineCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_machine.company_id
     *
     * @return the value of vege_machine.company_id
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_machine.company_id
     *
     * @param companyId the value for vege_machine.company_id
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_machine.company_name
     *
     * @return the value of vege_machine.company_name
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_machine.company_name
     *
     * @param companyName the value for vege_machine.company_name
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_machine.is_valid
     *
     * @return the value of vege_machine.is_valid
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_machine.is_valid
     *
     * @param isValid the value for vege_machine.is_valid
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }
}