package com.vcooline.crm.common.model

class VegeProdect extends BaseModel implements Serializable {
    /**
     * 主键
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    Integer id

    /**
     * 商品分类标识
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    Integer categoryId

    /**
     * 商品分类标识
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    String caregoryName

    /**
     * 商品编码
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    String number

    /**
     * 商品名称
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    String name

    /**
     * 商品条码
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    String barcode

    /**
     * 单位
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    String unit

    /**
     * 价格
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    Double price

    /**
     * 是否称重 false 代表不需要，true 代表需要
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    String allowWeigh

    /**
     * 店铺标识
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    Integer shopId

    /**
     * 店铺名称
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    String shopName

    /**
     * 卖方标识
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    String sellerId

    /**
     * 卖方名称
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    String sellerName

    /**
     * 创建时间
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    Date creationTime

    /**
     * 更新时间
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    Date updateTime

    /**
     * 产地
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    String placeOfOrigin

    /**
     * 规格
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    String specification

    /**
     * 商品等级
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    String grade

    /**
     * 促销标记 0代表不促销
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    Byte promotionFlag

    /**
     * 促销价格
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    Double promotionPrice

    /**
     * 促销开始时间
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    Date promoTimeFrom

    /**
     * 促销结束时间
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    Date promoTimeTo

    /**
     * 追溯码URL
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    String traceCode

    /**
     * 产品图 多图片用“|”分割
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    String photo

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vege_product
     *
     * @mbggenerated Tue Oct 10 23:00:17 CST 2017
     */
    static final long serialVersionUID = 1L

    @Override
    public String toString() {
        return "VegeProdect{" +
                "id=" + id +
                ", categoryId=" + categoryId +
                ", caregoryName='" + caregoryName + '\'' +
                ", number='" + number + '\'' +
                ", name='" + name + '\'' +
                ", barcode='" + barcode + '\'' +
                ", unit='" + unit + '\'' +
                ", price=" + price +
                ", allowWeigh='" + allowWeigh + '\'' +
                ", shopId=" + shopId +
                ", shopName='" + shopName + '\'' +
                ", sellerId='" + sellerId + '\'' +
                ", sellerName='" + sellerName + '\'' +
                ", creationTime=" + creationTime +
                ", updateTime=" + updateTime +
                ", placeOfOrigin='" + placeOfOrigin + '\'' +
                ", specification='" + specification + '\'' +
                ", grade='" + grade + '\'' +
                ", promotionFlag=" + promotionFlag +
                ", promotionPrice=" + promotionPrice +
                ", promoTimeFrom=" + promoTimeFrom +
                ", promoTimeTo=" + promoTimeTo +
                ", traceCode='" + traceCode + '\'' +
                ", photo='" + photo + '\'' +
                '}';
    }
}
