package com.vcooline.crm.common.model;

import java.io.Serializable;
import java.util.Date;

public class VegeAdPositionid extends BaseModel implements Serializable {
    /**
     * 主键 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer id;

    /**
     * 创建时间 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Date createDate;

    /**
     * 修改时间 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Date modifyDate;

    /**
     * 创建人 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String creator;

    /**
     * 修改人 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String modifier;

    /**
     * 广告位描述 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String positiondesc;

    /**
     * 广告位类型 1图片，2文字
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer advType;

    /**
     * 广告位内容 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String content;

    /**
     * 广告位名称 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private String positionName;

    /**
     * 是否首页展示 0展示，1不展示
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Byte showIndex;

    /**
     * 是否有效 1代表有效,0代表失效已删除
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Byte isValid;

    /**
     * 系统公司编号 
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private Integer sysCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vege_ad_positionid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_ad_positionid.id
     *
     * @return the value of vege_ad_positionid.id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_ad_positionid.id
     *
     * @param id the value for vege_ad_positionid.id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_ad_positionid.create_date
     *
     * @return the value of vege_ad_positionid.create_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_ad_positionid.create_date
     *
     * @param createDate the value for vege_ad_positionid.create_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_ad_positionid.modify_date
     *
     * @return the value of vege_ad_positionid.modify_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_ad_positionid.modify_date
     *
     * @param modifyDate the value for vege_ad_positionid.modify_date
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_ad_positionid.creator
     *
     * @return the value of vege_ad_positionid.creator
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_ad_positionid.creator
     *
     * @param creator the value for vege_ad_positionid.creator
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_ad_positionid.modifier
     *
     * @return the value of vege_ad_positionid.modifier
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_ad_positionid.modifier
     *
     * @param modifier the value for vege_ad_positionid.modifier
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_ad_positionid.positionDesc
     *
     * @return the value of vege_ad_positionid.positionDesc
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getPositiondesc() {
        return positiondesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_ad_positionid.positionDesc
     *
     * @param positiondesc the value for vege_ad_positionid.positionDesc
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setPositiondesc(String positiondesc) {
        this.positiondesc = positiondesc == null ? null : positiondesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_ad_positionid.adv_type
     *
     * @return the value of vege_ad_positionid.adv_type
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getAdvType() {
        return advType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_ad_positionid.adv_type
     *
     * @param advType the value for vege_ad_positionid.adv_type
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setAdvType(Integer advType) {
        this.advType = advType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_ad_positionid.content
     *
     * @return the value of vege_ad_positionid.content
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_ad_positionid.content
     *
     * @param content the value for vege_ad_positionid.content
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_ad_positionid.position_name
     *
     * @return the value of vege_ad_positionid.position_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_ad_positionid.position_name
     *
     * @param positionName the value for vege_ad_positionid.position_name
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_ad_positionid.show_index
     *
     * @return the value of vege_ad_positionid.show_index
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Byte getShowIndex() {
        return showIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_ad_positionid.show_index
     *
     * @param showIndex the value for vege_ad_positionid.show_index
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setShowIndex(Byte showIndex) {
        this.showIndex = showIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_ad_positionid.is_valid
     *
     * @return the value of vege_ad_positionid.is_valid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_ad_positionid.is_valid
     *
     * @param isValid the value for vege_ad_positionid.is_valid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vege_ad_positionid.sys_company_id
     *
     * @return the value of vege_ad_positionid.sys_company_id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public Integer getSysCompanyId() {
        return sysCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vege_ad_positionid.sys_company_id
     *
     * @param sysCompanyId the value for vege_ad_positionid.sys_company_id
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    public void setSysCompanyId(Integer sysCompanyId) {
        this.sysCompanyId = sysCompanyId;
    }
}