package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.CrmAllocationLog;

import java.util.List;

public interface CrmAllocationLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_allocation_log
     *
     * @mbggenerated Fri Jul 24 16:50:38 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_allocation_log
     *
     * @mbggenerated Fri Jul 24 16:50:38 CST 2015
     */
    int insert(CrmAllocationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_allocation_log
     *
     * @mbggenerated Fri Jul 24 16:50:38 CST 2015
     */
    int insertSelective(CrmAllocationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_allocation_log
     *
     * @mbggenerated Fri Jul 24 16:50:38 CST 2015
     */
    CrmAllocationLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_allocation_log
     *
     * @mbggenerated Fri Jul 24 16:50:38 CST 2015
     */
    int updateByPrimaryKeySelective(CrmAllocationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_allocation_log
     *
     * @mbggenerated Fri Jul 24 16:50:38 CST 2015
     */
    int updateByPrimaryKey(CrmAllocationLog record);

    /**
     * 根据目标Id查询线索或商机的分配记录
     *
     * @param record
     * @return
     */
    List<CrmAllocationLog> selectListByTargetId(CrmAllocationLog record);
}