package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.CrmAutharea;

public interface CrmAuthareaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_autharea
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_autharea
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int insert(CrmAutharea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_autharea
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int insertSelective(CrmAutharea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_autharea
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    CrmAutharea selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_autharea
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int updateByPrimaryKeySelective(CrmAutharea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_autharea
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int updateByPrimaryKey(CrmAutharea record);
}