package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.CrmAuth;

import java.util.List;

public interface CrmAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_auth
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_auth
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int insert(CrmAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_auth
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int insertSelective(CrmAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_auth
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    CrmAuth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_auth
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int updateByPrimaryKeySelective(CrmAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_auth
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int updateByPrimaryKey(CrmAuth record);

    /**
     * @return List<CrmAuth>    返回类型
     * @throws
     * @Description:查询全部菜单权限
     * @author caohuan
     * @date 2015年7月16日 下午5:17:43
     * 上海微客来软件技术有限公司
     */
    List<CrmAuth> getMenuAuthList();

    /**
     * @param @return 设定文件
     * @return List<CrmAuth>    返回类型
     * @throws
     * @Description:根据用户查询菜单权限
     * @author caohuan
     * @date 2015年7月22日 上午11:57:24
     * 上海微客来软件技术有限公司
     */
    List<CrmAuth> getMenuAuthListByAdmin(String adminId);

    /**
     * @return List<CrmAuth>    返回类型
     * @throws
     * @Description:获取系统所有权限（包含按钮和菜单权限）
     * @author caohuan
     * @date 2015年8月6日 上午11:59:14
     * 上海微客来软件技术有限公司
     */
    List<CrmAuth> getAllAuthList();

    /**
     * @param adminId
     * @return List<CrmAuth>    返回类型
     * @throws
     * @Description:根据用户查询所有权限
     * @author caohuan
     * @date 2015年8月6日 下午3:58:15
     * 上海微客来软件技术有限公司
     */
    List<CrmAuth> getAllAuthListByAdmin(String adminId);
}