package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.CrmCallback;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CrmCallbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_callback
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_callback
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int insert(CrmCallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_callback
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int insertSelective(CrmCallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_callback
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    CrmCallback selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_callback
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int updateByPrimaryKeySelective(CrmCallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_callback
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int updateByPrimaryKey(CrmCallback record);

    /**
     * 根据线索ID查询该线索最后一条回访记录
     *
     * @param clueId
     * @return
     */
    CrmCallback selectLastCallback(Long clueId);

    /**
     * 根据线索ID查询该线索最后一条回访记录(倒序)
     *
     * @param targetId
     * @param releType
     * @return
     */
    List<CrmCallback> selectCallBackListByTarget(@Param("targetId") Long targetId, @Param("releType") Byte releType);
}