package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.CrmContractFile;

import java.util.List;

public interface CrmContractFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_contract_file
     *
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_contract_file
     *
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    int insert(CrmContractFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_contract_file
     *
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    int insertSelective(CrmContractFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_contract_file
     *
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    CrmContractFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_contract_file
     *
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    int updateByPrimaryKeySelective(CrmContractFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_contract_file
     *
     * @mbggenerated Wed Nov 11 15:36:25 CST 2015
     */
    int updateByPrimaryKey(CrmContractFile record);

    /**
     * 根据type 和 targetId查询合同
     * @param record
     * @return
     */
    List<CrmContractFile> selectByTypeTargetId(CrmContractFile record);
}