package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.CrmCustomer;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CrmCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int insert(CrmCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int insertSelective(CrmCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    CrmCustomer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int updateByPrimaryKeySelective(CrmCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_customer
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int updateByPrimaryKey(CrmCustomer record);

    /**
     * 根据线索ID查询该线索的联系人
     * @param targetId
     * @return
     */
    List<CrmCustomer> getCustlistByClueId(@Param("targetId")Long targetId,@Param("releType")Byte releType);

    /**
     * 根据手机号模糊查询客户信息
     * @param custPhone
     * @return
     */
    List<CrmCustomer> getCustListByPhone(@Param("custPhone")String custPhone);
}