package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.CrmProductVersion;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CrmProductVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_product_version
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_product_version
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int insert(CrmProductVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_product_version
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int insertSelective(CrmProductVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_product_version
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    CrmProductVersion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_product_version
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int updateByPrimaryKeySelective(CrmProductVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_product_version
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int updateByPrimaryKey(CrmProductVersion record);

    /**
     * 根据条件查询版本信息
     *
     * @param record
     * @return
     */
    List<CrmProductVersion> getList(CrmProductVersion record);

    /**
     * @return List<CrmProductVersion>    返回类型
     * @throws
     * @Description:获取所有套餐列表
     * @author caohuan
     * @date 2015年7月29日 下午3:42:01
     * 上海微客来软件技术有限公司
     */
    List<CrmProductVersion> getVersionList();


    /**
     * 根据商机ID查询关联套餐
     *
     * @param busiId
     * @return
     */
    List<CrmProductVersion> getVersionListByBusiId(@Param("busiId") Long busiId);
}