package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.CrmReleCust;

public interface CrmReleCustMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_clue_cust
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_clue_cust
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int insert(CrmReleCust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_clue_cust
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int insertSelective(CrmReleCust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_clue_cust
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    CrmReleCust selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_clue_cust
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int updateByPrimaryKeySelective(CrmReleCust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_clue_cust
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int updateByPrimaryKey(CrmReleCust record);
}