package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.CrmReleVersion;

public interface CrmReleVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_rele_version
     *
     * @mbggenerated Thu Jul 30 15:40:22 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_rele_version
     *
     * @mbggenerated Thu Jul 30 15:40:22 CST 2015
     */
    int insert(CrmReleVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_rele_version
     *
     * @mbggenerated Thu Jul 30 15:40:22 CST 2015
     */
    int insertSelective(CrmReleVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_rele_version
     *
     * @mbggenerated Thu Jul 30 15:40:22 CST 2015
     */
    CrmReleVersion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_rele_version
     *
     * @mbggenerated Thu Jul 30 15:40:22 CST 2015
     */
    int updateByPrimaryKeySelective(CrmReleVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_rele_version
     *
     * @mbggenerated Thu Jul 30 15:40:22 CST 2015
     */
    int updateByPrimaryKey(CrmReleVersion record);
}