package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.CrmRoleAuth;

import java.util.Map;

public interface CrmRoleAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role_auth
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role_auth
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int insert(CrmRoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role_auth
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int insertSelective(CrmRoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role_auth
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    CrmRoleAuth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role_auth
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int updateByPrimaryKeySelective(CrmRoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role_auth
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int updateByPrimaryKey(CrmRoleAuth record);

    /**
     * @param roleAuthList
     * @return int    返回类型
     * @throws
     * @Description:批量插入角色权限管理数据
     * @author caohuan
     * @date 2015年7月21日 上午10:58:04
     * 上海微客来软件技术有限公司
     */
    int batchInsert(Map<String, Object> roleAuthList);


    /**
     * @param id
     * @param @return 设定文件
     * @return int    返回类型
     * @throws
     * @Description:根据角色删除关联的权限
     * @author caohuan
     * @date 2015年7月28日 上午10:35:36
     * 上海微客来软件技术有限公司
     */
    int deleteAuthByRole(Long id);

}