package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.Districts;

public interface DistrictsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table districts
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table districts
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int insert(Districts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table districts
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int insertSelective(Districts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table districts
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    Districts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table districts
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int updateByPrimaryKeySelective(Districts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table districts
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int updateByPrimaryKey(Districts record);
}