package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.Provinces;

public interface ProvincesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int insert(Provinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int insertSelective(Provinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    Provinces selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int updateByPrimaryKeySelective(Provinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int updateByPrimaryKey(Provinces record);
}