package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.VegeTrace;

public interface VegeTraceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_trace
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_trace
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int insert(VegeTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_trace
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int insertSelective(VegeTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_trace
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    VegeTrace selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_trace
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int updateByPrimaryKeySelective(VegeTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_trace
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(VegeTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_trace
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int updateByPrimaryKey(VegeTrace record);
}