package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.VegeSysCompany;

public interface VegeSysCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_sys_company
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_sys_company
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int insert(VegeSysCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_sys_company
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int insertSelective(VegeSysCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_sys_company
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    VegeSysCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_sys_company
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int updateByPrimaryKeySelective(VegeSysCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_sys_company
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int updateByPrimaryKey(VegeSysCompany record);
}