package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.VegeVendor;

public interface VegeVendorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_vendor
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_vendor
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int insert(VegeVendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_vendor
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int insertSelective(VegeVendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_vendor
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    VegeVendor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_vendor
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int updateByPrimaryKeySelective(VegeVendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_vendor
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int updateByPrimaryKey(VegeVendor record);
}