package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.VegeWorker;

public interface VegeWorkerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_worker
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_worker
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int insert(VegeWorker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_worker
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int insertSelective(VegeWorker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_worker
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    VegeWorker selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_worker
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int updateByPrimaryKeySelective(VegeWorker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_worker
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int updateByPrimaryKey(VegeWorker record);
}