package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.VegeAdPositionid;

public interface VegeAdPositionidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_ad_positionid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_ad_positionid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int insert(VegeAdPositionid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_ad_positionid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int insertSelective(VegeAdPositionid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_ad_positionid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    VegeAdPositionid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_ad_positionid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int updateByPrimaryKeySelective(VegeAdPositionid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_ad_positionid
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int updateByPrimaryKey(VegeAdPositionid record);
}