package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.VegeRaffle;

public interface VegeRaffleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_raffle
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_raffle
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int insert(VegeRaffle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_raffle
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int insertSelective(VegeRaffle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_raffle
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    VegeRaffle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_raffle
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int updateByPrimaryKeySelective(VegeRaffle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_raffle
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int updateByPrimaryKey(VegeRaffle record);
}