package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.VegeVendorExt;

public interface VegeVendorExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_vendor_ext
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_vendor_ext
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int insert(VegeVendorExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_vendor_ext
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int insertSelective(VegeVendorExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_vendor_ext
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    VegeVendorExt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_vendor_ext
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int updateByPrimaryKeySelective(VegeVendorExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_vendor_ext
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int updateByPrimaryKey(VegeVendorExt record);
}