package com.vcooline.crm.common.mapper;

import com.vcooline.crm.common.model.VegeSysUser;

public interface VegeSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_sys_user
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_sys_user
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int insert(VegeSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_sys_user
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int insertSelective(VegeSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_sys_user
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    VegeSysUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_sys_user
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int updateByPrimaryKeySelective(VegeSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_sys_user
     *
     * @mbggenerated Sun Oct 15 15:29:20 CST 2017
     */
    int updateByPrimaryKey(VegeSysUser record);
}