package com.vcooline.crm.admin.service;

import com.vcooline.crm.common.model.CrmBusiProduct;
import com.vcooline.crm.common.model.CrmBusiness;
import com.vcooline.crm.common.model.CrmCustomer;
import com.vcooline.crm.common.model.Page;
import com.vcooline.crm.common.pojo.BusinessForm;

import java.util.List;

/**
 * 上级service
 * Created by xinbaojian on 15/7/28.
 */
public interface CrmBusinessService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_business
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_business
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    int insert(CrmBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_business
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    int insertSelective(CrmBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_business
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    CrmBusiness selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_business
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    int updateByPrimaryKeySelective(CrmBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_business
     *
     * @mbggenerated Wed Jul 22 10:16:27 CST 2015
     */
    int updateByPrimaryKey(CrmBusiness record);

    /**
     * 获取当前自增码最大值
     * @return
     */
    Integer getMaxNumCode();

    /**
     * 根据线索转换商机
     * @param clueId
     * @return
     */
    int convertBusinessFormClue(Long clueId,List<CrmBusiProduct> busiProducts);

    /**
     * 分页查询商机西诺西
     * @param business 查询条件
     * @param pageNo 当前页
     * @param pageSize 每页条数
     * @return
     */
    Page<CrmBusiness> queryBusinessByPage(CrmBusiness business,Integer pageNo,Integer pageSize);

    /**
     * 保存或更新商机
     * @param form
     * @return
     */
    int updateBusiness(BusinessForm form);

    /**
     * 审核商机
     * @param busiId 要审核的商机ID
     * @param pass 是否通过审核
     * @param remark
     */
    Boolean auditingBusiness(Long busiId, Boolean pass, String remark);

}
