package com.vcooline.crm.admin.service;

import com.vcooline.crm.common.model.CrmContProduct;

/**
 * Created by xinbaojian on 15/8/4.
 */
public interface CrmContProductService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_cont_product
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_cont_product
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int insert(CrmContProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_cont_product
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int insertSelective(CrmContProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_cont_product
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    CrmContProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_cont_product
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int updateByPrimaryKeySelective(CrmContProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_cont_product
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int updateByPrimaryKey(CrmContProduct record);
}
