package com.vcooline.crm.admin.service;

import com.vcooline.crm.common.model.CrmCallback;

import java.util.List;

/**
 * 回访记录表
 * Created by xinbaojian on 15/7/24.
 */
public interface CrmCallbackService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_callback
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_callback
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int insert(CrmCallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_callback
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int insertSelective(CrmCallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_callback
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    CrmCallback selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_callback
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int updateByPrimaryKeySelective(CrmCallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_callback
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int updateByPrimaryKey(CrmCallback record);

    /**
     * 根据线索ID查询该线索最后一条回访记录
     *
     * @param clueId
     * @return
     */
    CrmCallback selectLastCallback(Long clueId);

    /**
     * 根据线索ID查询该线索最后一条回访记录(倒序)
     *
     * @param clueId
     * @param releType
     * @return
     */
    List<CrmCallback> selectCallBackListByClueId(Long clueId, Byte releType);

    /**
     * 根据商机ID，修改线索状态
     *
     * @param busiId
     * @return
     */
    boolean addFinshedStatus(Long busiId);
}
