package com.vcooline.crm.admin.service;

import com.vcooline.crm.common.model.CrmClueProduct;

/**
 * 线索产品关联表
 * Created by xinbaojian on 15/7/17.
 */
public interface CrmClueProductService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_clue_product
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_clue_product
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int insert(CrmClueProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_clue_product
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int insertSelective(CrmClueProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_clue_product
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    CrmClueProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_clue_product
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int updateByPrimaryKeySelective(CrmClueProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_clue_product
     *
     * @mbggenerated Thu Jul 16 15:20:21 CST 2015
     */
    int updateByPrimaryKey(CrmClueProduct record);

    /**
     * 根据线索ID删除线索产品关联
     *
     * @param clueId
     * @return
     */
    int deleteByClueId(Long clueId);
}
