package com.vcooline.crm.admin.service;

import com.vcooline.crm.common.model.CrmProductVersion;

import java.util.List;

/**
 * 产品套餐
 * Created by xinbaojian on 15/7/28.
 */
public interface CrmProductVersionService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_product_version
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_product_version
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int insert(CrmProductVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_product_version
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int insertSelective(CrmProductVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_product_version
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    CrmProductVersion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_product_version
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int updateByPrimaryKeySelective(CrmProductVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_product_version
     *
     * @mbggenerated Thu Jul 16 15:20:22 CST 2015
     */
    int updateByPrimaryKey(CrmProductVersion record);

    /**
     * 根据条件查询版本信息
     * @param record
     * @return
     */
    List<CrmProductVersion> getList(CrmProductVersion record);


    /**
     * 根据产品ID查询产品套餐信息
     * @param prodId
     * @return
     */
    List<CrmProductVersion> getListByProdId(Long prodId);

    /**
      * @Description:获取所有套餐列表
      * @return List<CrmProductVersion>    返回类型
      * @throws
      * @author caohuan
      * @date 2015年7月29日 下午3:39:33
      * 上海微客来软件技术有限公司
     */
    List<CrmProductVersion> getVersionList();


    List<CrmProductVersion> getVersionListByBusiId(Long busiId);

}
