package com.vcooline.crm.admin.service

import com.vcooline.crm.common.model.VegeMachine


interface IVegeMachineService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_machine
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_machine
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    int insert(VegeMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_machine
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    int insertSelective(VegeMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_machine
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    VegeMachine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_machine
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    int updateByPrimaryKeySelective(VegeMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vege_machine
     *
     * @mbggenerated Sun Oct 15 15:11:46 CST 2017
     */
    int updateByPrimaryKey(VegeMachine record);
}
